[
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1371226703",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/14121#issuecomment-1371226703",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/14121",
        "id": 1371226703,
        "node_id": "IC_kwDOCVq1mM5Ru0JP",
        "user": {
            "login": "faxu",
            "id": 20780999,
            "node_id": "MDQ6VXNlcjIwNzgwOTk5",
            "avatar_url": "https://avatars.githubusercontent.com/u/20780999?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/faxu",
            "html_url": "https://github.com/faxu",
            "followers_url": "https://api.github.com/users/faxu/followers",
            "following_url": "https://api.github.com/users/faxu/following{/other_user}",
            "gists_url": "https://api.github.com/users/faxu/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/faxu/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/faxu/subscriptions",
            "organizations_url": "https://api.github.com/users/faxu/orgs",
            "repos_url": "https://api.github.com/users/faxu/repos",
            "events_url": "https://api.github.com/users/faxu/events{/privacy}",
            "received_events_url": "https://api.github.com/users/faxu/received_events",
            "type": "User",
            "site_admin": true
        },
        "created_at": "2023-01-04T17:38:04Z",
        "updated_at": "2023-01-04T17:38:04Z",
        "author_association": "MEMBER",
        "body": "CC @wangxiyuan / @FFFrog ",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1371226703/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1371628519",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/14121#issuecomment-1371628519",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/14121",
        "id": 1371628519,
        "node_id": "IC_kwDOCVq1mM5RwWPn",
        "user": {
            "login": "wangxiyuan",
            "id": 10891919,
            "node_id": "MDQ6VXNlcjEwODkxOTE5",
            "avatar_url": "https://avatars.githubusercontent.com/u/10891919?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/wangxiyuan",
            "html_url": "https://github.com/wangxiyuan",
            "followers_url": "https://api.github.com/users/wangxiyuan/followers",
            "following_url": "https://api.github.com/users/wangxiyuan/following{/other_user}",
            "gists_url": "https://api.github.com/users/wangxiyuan/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/wangxiyuan/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/wangxiyuan/subscriptions",
            "organizations_url": "https://api.github.com/users/wangxiyuan/orgs",
            "repos_url": "https://api.github.com/users/wangxiyuan/repos",
            "events_url": "https://api.github.com/users/wangxiyuan/events{/privacy}",
            "received_events_url": "https://api.github.com/users/wangxiyuan/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-01-05T01:25:03Z",
        "updated_at": "2023-01-05T01:25:11Z",
        "author_association": "CONTRIBUTOR",
        "body": "> CC @wangxiyuan / @FFFrog\r\n\r\nThanks for reminding. @FFFrog has a patch to fix the issue already. https://github.com/microsoft/onnxruntime/pull/14058",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1371628519/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1373373295",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/14121#issuecomment-1373373295",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/14121",
        "id": 1373373295,
        "node_id": "IC_kwDOCVq1mM5R3ANv",
        "user": {
            "login": "luoyangen",
            "id": 3061079,
            "node_id": "MDQ6VXNlcjMwNjEwNzk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3061079?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/luoyangen",
            "html_url": "https://github.com/luoyangen",
            "followers_url": "https://api.github.com/users/luoyangen/followers",
            "following_url": "https://api.github.com/users/luoyangen/following{/other_user}",
            "gists_url": "https://api.github.com/users/luoyangen/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/luoyangen/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/luoyangen/subscriptions",
            "organizations_url": "https://api.github.com/users/luoyangen/orgs",
            "repos_url": "https://api.github.com/users/luoyangen/repos",
            "events_url": "https://api.github.com/users/luoyangen/events{/privacy}",
            "received_events_url": "https://api.github.com/users/luoyangen/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-01-06T09:07:21Z",
        "updated_at": "2023-01-06T09:07:36Z",
        "author_association": "NONE",
        "body": "> > CC @wangxiyuan / @FFFrog\r\n> \r\n> Thanks for reminding. @FFFrog has a patch to fix the issue already. #14058\r\n\r\nThanks. I tried to use the full directory \"cann\" of the branch \"multi-stream\" of project https://github.com/learningbackup/onnxruntime.git, but still have error while compiling. The error details are:\r\n\r\n`\r\nonnxruntime/core/providers/cann/cann_call.cc:111:22: 错误：‘GRAPH_INVALID_IR_DEF’在此作用域中尚未声明\r\n  111 |     CASE_ENUM_TO_STR(GRAPH_INVALID_IR_DEF);\r\n      |                      ^~~~~~~~~~~~~~~~~~~~\r\n`\r\n\r\n`\r\nonnxruntime/core/providers/cann/cann_call.cc:112:22: 错误：‘OP_WITHOUT_IR_DATATYPE_INFER_RULE’在此作用域中尚未声明\r\n  112 |     CASE_ENUM_TO_STR(OP_WITHOUT_IR_DATATYPE_INFER_RULE);\r\n      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n`",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1373373295/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1373383271",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/14121#issuecomment-1373383271",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/14121",
        "id": 1373383271,
        "node_id": "IC_kwDOCVq1mM5R3Cpn",
        "user": {
            "login": "FFFrog",
            "id": 85333600,
            "node_id": "MDQ6VXNlcjg1MzMzNjAw",
            "avatar_url": "https://avatars.githubusercontent.com/u/85333600?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/FFFrog",
            "html_url": "https://github.com/FFFrog",
            "followers_url": "https://api.github.com/users/FFFrog/followers",
            "following_url": "https://api.github.com/users/FFFrog/following{/other_user}",
            "gists_url": "https://api.github.com/users/FFFrog/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/FFFrog/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/FFFrog/subscriptions",
            "organizations_url": "https://api.github.com/users/FFFrog/orgs",
            "repos_url": "https://api.github.com/users/FFFrog/repos",
            "events_url": "https://api.github.com/users/FFFrog/events{/privacy}",
            "received_events_url": "https://api.github.com/users/FFFrog/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-01-06T09:18:08Z",
        "updated_at": "2023-01-06T09:20:29Z",
        "author_association": "CONTRIBUTOR",
        "body": "> > > CC @wangxiyuan / @FFFrog\r\n> > \r\n> > \r\n> > Thanks for reminding. @FFFrog has a patch to fix the issue already. #14058\r\n> \r\n> Thanks. I tried to use the full directory \"cann\" of the branch \"multi-stream\" of project https://github.com/learningbackup/onnxruntime.git, but still have error while compiling. The error details are:\r\n> \r\n> `onnxruntime/core/providers/cann/cann_call.cc:111:22: 错误：‘GRAPH_INVALID_IR_DEF’在此作用域中尚未声明 111 | CASE_ENUM_TO_STR(GRAPH_INVALID_IR_DEF); | ^~~~~~~~~~~~~~~~~~~~`\r\n> \r\n> `onnxruntime/core/providers/cann/cann_call.cc:112:22: 错误：‘OP_WITHOUT_IR_DATATYPE_INFER_RULE’在此作用域中尚未声明 112 | CASE_ENUM_TO_STR(OP_WITHOUT_IR_DATATYPE_INFER_RULE); | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`\r\n\r\nSo sorry for that, could you show me the **cann** version you are using?\r\nIf possible, please upgrade CANN to [the latest version](https://www.hiascend.com/en/software/cann/community)",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1373383271/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1374314467",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/14121#issuecomment-1374314467",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/14121",
        "id": 1374314467,
        "node_id": "IC_kwDOCVq1mM5R6l_j",
        "user": {
            "login": "luoyangen",
            "id": 3061079,
            "node_id": "MDQ6VXNlcjMwNjEwNzk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3061079?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/luoyangen",
            "html_url": "https://github.com/luoyangen",
            "followers_url": "https://api.github.com/users/luoyangen/followers",
            "following_url": "https://api.github.com/users/luoyangen/following{/other_user}",
            "gists_url": "https://api.github.com/users/luoyangen/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/luoyangen/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/luoyangen/subscriptions",
            "organizations_url": "https://api.github.com/users/luoyangen/orgs",
            "repos_url": "https://api.github.com/users/luoyangen/repos",
            "events_url": "https://api.github.com/users/luoyangen/events{/privacy}",
            "received_events_url": "https://api.github.com/users/luoyangen/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-01-07T00:45:17Z",
        "updated_at": "2023-01-07T00:45:17Z",
        "author_association": "NONE",
        "body": "> > > > CC @wangxiyuan / @FFFrog\r\n> > > \r\n> > > \r\n> > > Thanks for reminding. @FFFrog has a patch to fix the issue already. #14058\r\n> > \r\n> > \r\n> > Thanks. I tried to use the full directory \"cann\" of the branch \"multi-stream\" of project https://github.com/learningbackup/onnxruntime.git, but still have error while compiling. The error details are:\r\n> > `onnxruntime/core/providers/cann/cann_call.cc:111:22: 错误：‘GRAPH_INVALID_IR_DEF’在此作用域中尚未声明 111 | CASE_ENUM_TO_STR(GRAPH_INVALID_IR_DEF); | ^~~~~~~~~~~~~~~~~~~~`\r\n> > `onnxruntime/core/providers/cann/cann_call.cc:112:22: 错误：‘OP_WITHOUT_IR_DATATYPE_INFER_RULE’在此作用域中尚未声明 112 | CASE_ENUM_TO_STR(OP_WITHOUT_IR_DATATYPE_INFER_RULE); | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`\r\n> \r\n> So sorry for that, could you show me the **cann** version you are using? If possible, please upgrade CANN to [the latest version](https://www.hiascend.com/en/software/cann/community)\r\n\r\nCANN version is 5.1.RC2.\r\nI shall upgrade CANN.\r\nThanks.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1374314467/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1381233585",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/14121#issuecomment-1381233585",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/14121",
        "id": 1381233585,
        "node_id": "IC_kwDOCVq1mM5SU_Ox",
        "user": {
            "login": "luoyangen",
            "id": 3061079,
            "node_id": "MDQ6VXNlcjMwNjEwNzk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3061079?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/luoyangen",
            "html_url": "https://github.com/luoyangen",
            "followers_url": "https://api.github.com/users/luoyangen/followers",
            "following_url": "https://api.github.com/users/luoyangen/following{/other_user}",
            "gists_url": "https://api.github.com/users/luoyangen/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/luoyangen/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/luoyangen/subscriptions",
            "organizations_url": "https://api.github.com/users/luoyangen/orgs",
            "repos_url": "https://api.github.com/users/luoyangen/repos",
            "events_url": "https://api.github.com/users/luoyangen/events{/privacy}",
            "received_events_url": "https://api.github.com/users/luoyangen/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-01-13T02:26:25Z",
        "updated_at": "2023-01-13T02:26:25Z",
        "author_association": "NONE",
        "body": "> > > > CC @wangxiyuan / @FFFrog\r\n> > > \r\n> > > \r\n> > > Thanks for reminding. @FFFrog has a patch to fix the issue already. #14058\r\n> > \r\n> > \r\n> > Thanks. I tried to use the full directory \"cann\" of the branch \"multi-stream\" of project https://github.com/learningbackup/onnxruntime.git, but still have error while compiling. The error details are:\r\n> > `onnxruntime/core/providers/cann/cann_call.cc:111:22: 错误：‘GRAPH_INVALID_IR_DEF’在此作用域中尚未声明 111 | CASE_ENUM_TO_STR(GRAPH_INVALID_IR_DEF); | ^~~~~~~~~~~~~~~~~~~~`\r\n> > `onnxruntime/core/providers/cann/cann_call.cc:112:22: 错误：‘OP_WITHOUT_IR_DATATYPE_INFER_RULE’在此作用域中尚未声明 112 | CASE_ENUM_TO_STR(OP_WITHOUT_IR_DATATYPE_INFER_RULE); | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`\r\n> \r\n> So sorry for that, could you show me the **cann** version you are using? If possible, please upgrade CANN to [the latest version](https://www.hiascend.com/en/software/cann/community)\r\n\r\nHi, after cann updated to 6.0.RC1, it successed complied, but cannot pass all the test steps. The error message is:\r\n`\r\nThe following tests FAILED:\r\n\t  1 - onnxruntime_test_all (Failed)\r\nErrors while running CTest\r\nOutput from these tests are in: /root/onnxruntime/build/Linux/RelWithDebInfo/Testing/Temporary/LastTest.log\r\nUse \"--rerun-failed --output-on-failure\" to re-run the failed cases verbosely.\r\nTraceback (most recent call last):\r\n  File \"/root/onnxruntime/tools/ci_build/build.py\", line 2880, in <module>\r\n    sys.exit(main())\r\n  File \"/root/onnxruntime/tools/ci_build/build.py\", line 2785, in main\r\n    run_onnxruntime_tests(args, source_dir, ctest_path, build_dir, configs)\r\n  File \"/root/onnxruntime/tools/ci_build/build.py\", line 1900, in run_onnxruntime_tests\r\n    run_subprocess(ctest_cmd, cwd=cwd, dll_path=dll_path)\r\n  File \"/root/onnxruntime/tools/ci_build/build.py\", line 760, in run_subprocess\r\n    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)\r\n  File \"/root/onnxruntime/tools/python/util/run.py\", line 49, in run\r\n    completed_process = subprocess.run(\r\n  File \"/root/miniconda3/envs/onnx_runtime2/lib/python3.9/subprocess.py\", line 528, in run\r\n    raise CalledProcessError(retcode, process.args,subprocess.CalledProcessError: Command '['/root/miniconda3/envs/onnx_runti\r\n[LastTestsFailed.log](https://github.com/microsoft/onnxruntime/files/10407606/LastTestsFailed.log)\r\n[CTestCostData.txt](https://github.com/microsoft/onnxruntime/files/10407607/CTestCostData.txt)\r\nme2/bin/ctest', '--build-config', 'RelWithDebInfo', '--verbose', '--timeout', '10800']' returned non-zero exit status 8.\r\n`\r\n\r\nAnd the test logs file is\r\n[LastTest.log](https://github.com/microsoft/onnxruntime/files/10407603/LastTest.log)\r\n",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1381233585/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1381256489",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/14121#issuecomment-1381256489",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/14121",
        "id": 1381256489,
        "node_id": "IC_kwDOCVq1mM5SVE0p",
        "user": {
            "login": "wangxiyuan",
            "id": 10891919,
            "node_id": "MDQ6VXNlcjEwODkxOTE5",
            "avatar_url": "https://avatars.githubusercontent.com/u/10891919?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/wangxiyuan",
            "html_url": "https://github.com/wangxiyuan",
            "followers_url": "https://api.github.com/users/wangxiyuan/followers",
            "following_url": "https://api.github.com/users/wangxiyuan/following{/other_user}",
            "gists_url": "https://api.github.com/users/wangxiyuan/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/wangxiyuan/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/wangxiyuan/subscriptions",
            "organizations_url": "https://api.github.com/users/wangxiyuan/orgs",
            "repos_url": "https://api.github.com/users/wangxiyuan/repos",
            "events_url": "https://api.github.com/users/wangxiyuan/events{/privacy}",
            "received_events_url": "https://api.github.com/users/wangxiyuan/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-01-13T03:06:53Z",
        "updated_at": "2023-01-13T03:06:53Z",
        "author_association": "CONTRIBUTOR",
        "body": "The error log is:\r\n\r\n```\r\n[ RUN      ] CannExecutionProviderTest.FunctionTest\r\nTraceback (most recent call last):\r\n  File \"/usr/local/Ascend/ascend-toolkit/6.0.RC1/python/site-packages/tbe/tvm/target.py\", line 67, in <module>\r\n    from decorator import decorate\r\nModuleNotFoundError: No module named 'decorator'\r\n```\r\nSo please follow the message to install `decorator` package first. It is a dependences missing problem for ascend toolkit. For this kind of error, I assume you can fix it locally first. Thanks.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1381256489/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1381259164",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/14121#issuecomment-1381259164",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/14121",
        "id": 1381259164,
        "node_id": "IC_kwDOCVq1mM5SVFec",
        "user": {
            "login": "luoyangen",
            "id": 3061079,
            "node_id": "MDQ6VXNlcjMwNjEwNzk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3061079?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/luoyangen",
            "html_url": "https://github.com/luoyangen",
            "followers_url": "https://api.github.com/users/luoyangen/followers",
            "following_url": "https://api.github.com/users/luoyangen/following{/other_user}",
            "gists_url": "https://api.github.com/users/luoyangen/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/luoyangen/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/luoyangen/subscriptions",
            "organizations_url": "https://api.github.com/users/luoyangen/orgs",
            "repos_url": "https://api.github.com/users/luoyangen/repos",
            "events_url": "https://api.github.com/users/luoyangen/events{/privacy}",
            "received_events_url": "https://api.github.com/users/luoyangen/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-01-13T03:11:02Z",
        "updated_at": "2023-01-13T03:11:02Z",
        "author_association": "NONE",
        "body": "> The error log is:\r\n> \r\n> ```\r\n> [ RUN      ] CannExecutionProviderTest.FunctionTest\r\n> Traceback (most recent call last):\r\n>   File \"/usr/local/Ascend/ascend-toolkit/6.0.RC1/python/site-packages/tbe/tvm/target.py\", line 67, in <module>\r\n>     from decorator import decorate\r\n> ModuleNotFoundError: No module named 'decorator'\r\n> ```\r\n> \r\n> So please follow the message to install `decorator` package first. It is a dependences missing problem for ascend toolkit. For this kind of error, I assume you can fix it locally first. Thanks.\r\n\r\noooh! My bad! Didn't figure out the error message~Thanks!",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1381259164/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1407590358",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/14121#issuecomment-1407590358",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/14121",
        "id": 1407590358,
        "node_id": "IC_kwDOCVq1mM5T5h_W",
        "user": {
            "login": "luoyangen",
            "id": 3061079,
            "node_id": "MDQ6VXNlcjMwNjEwNzk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3061079?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/luoyangen",
            "html_url": "https://github.com/luoyangen",
            "followers_url": "https://api.github.com/users/luoyangen/followers",
            "following_url": "https://api.github.com/users/luoyangen/following{/other_user}",
            "gists_url": "https://api.github.com/users/luoyangen/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/luoyangen/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/luoyangen/subscriptions",
            "organizations_url": "https://api.github.com/users/luoyangen/orgs",
            "repos_url": "https://api.github.com/users/luoyangen/repos",
            "events_url": "https://api.github.com/users/luoyangen/events{/privacy}",
            "received_events_url": "https://api.github.com/users/luoyangen/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-01-29T07:49:23Z",
        "updated_at": "2023-01-29T07:49:23Z",
        "author_association": "NONE",
        "body": "@wangxiyuan Hi, Sorry to bother again.\r\nAfter the decorator package installed, I successed to compile and install onnxruntime-cann. \r\nBut still have some error while using cann provider in the onnxruntime。\r\nThe provider configuration is:\r\n\r\n`\r\nproviders = [\r\n    ('CANNExecutionProvider', {\r\n        'device_id': 1,\r\n        'max_opqueue_num': 10000,\r\n        'arena_extend_strategy': 'kNextPowerOfTwo',\r\n        'npu_mem_limit': 2 * 1024 * 1024 * 1024,\r\n        'do_copy_in_default_stream': True,\r\n    }),\r\n]`\r\n\r\nand the error info is:\r\n![image](https://user-images.githubusercontent.com/3061079/215312628-9e95e20f-6fc0-49ce-a217-3a8c112ed96a.png)\r\n\r\nAnd the code works well while i change the provider to **CPUExecutionProvider**。\r\n\r\nAlso the ascend log file under the directory \"ascend/debug\" details are:\r\n**plog/plog-xxx.log:**\r\n![image](https://user-images.githubusercontent.com/3061079/215312788-bc742a94-26bd-4b3c-8484-da8b49cfc5cf.png)\r\n\r\n**device-0/device-xxx.log:**\r\n![image](https://user-images.githubusercontent.com/3061079/215312750-f8d660f2-a00b-4273-8460-2880059a7f30.png)\r\n\r\n",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1407590358/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1407595103",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/14121#issuecomment-1407595103",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/14121",
        "id": 1407595103,
        "node_id": "IC_kwDOCVq1mM5T5jJf",
        "user": {
            "login": "FFFrog",
            "id": 85333600,
            "node_id": "MDQ6VXNlcjg1MzMzNjAw",
            "avatar_url": "https://avatars.githubusercontent.com/u/85333600?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/FFFrog",
            "html_url": "https://github.com/FFFrog",
            "followers_url": "https://api.github.com/users/FFFrog/followers",
            "following_url": "https://api.github.com/users/FFFrog/following{/other_user}",
            "gists_url": "https://api.github.com/users/FFFrog/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/FFFrog/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/FFFrog/subscriptions",
            "organizations_url": "https://api.github.com/users/FFFrog/orgs",
            "repos_url": "https://api.github.com/users/FFFrog/repos",
            "events_url": "https://api.github.com/users/FFFrog/events{/privacy}",
            "received_events_url": "https://api.github.com/users/FFFrog/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-01-29T08:14:50Z",
        "updated_at": "2023-01-29T08:14:50Z",
        "author_association": "CONTRIBUTOR",
        "body": "> @wangxiyuan Hi, Sorry to bother again. After the decorator package installed, I successed to compile and install onnxruntime-cann. But still have some error while using cann provider in the onnxruntime。 The provider configuration is:\r\n> \r\n> ` providers = [ ('CANNExecutionProvider', { 'device_id': 1, 'max_opqueue_num': 10000, 'arena_extend_strategy': 'kNextPowerOfTwo', 'npu_mem_limit': 2 * 1024 * 1024 * 1024, 'do_copy_in_default_stream': True, }), ]`\r\n> \r\n> and the error info is: ![image](https://user-images.githubusercontent.com/3061079/215312628-9e95e20f-6fc0-49ce-a217-3a8c112ed96a.png)\r\n> \r\n> And the code works well while i change the provider to **CPUExecutionProvider**。\r\n> \r\n> Also the ascend log file under the directory \"ascend/debug\" details are: **plog/plog-xxx.log:** ![image](https://user-images.githubusercontent.com/3061079/215312788-bc742a94-26bd-4b3c-8484-da8b49cfc5cf.png)\r\n> \r\n> **device-0/device-xxx.log:** ![image](https://user-images.githubusercontent.com/3061079/215312750-f8d660f2-a00b-4273-8460-2880059a7f30.png)\r\n\r\nSo sorry for that.\r\n\r\nCan you refer to the [link](https://onnxruntime.ai/docs/execution-providers/community-maintained/CANN-ExecutionProvider.html#python) and try again? Pay attention to the ```providers``` field, please.\r\n\r\nIf there are still errors, please enable debug log of Ascend and mail the log to ```ljw1101.vip@gmail.com```. \r\n\r\nThank you\r\n",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1407595103/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1498611012",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/14121#issuecomment-1498611012",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/14121",
        "id": 1498611012,
        "node_id": "IC_kwDOCVq1mM5ZUv1E",
        "user": {
            "login": "xinxin12345",
            "id": 22726660,
            "node_id": "MDQ6VXNlcjIyNzI2NjYw",
            "avatar_url": "https://avatars.githubusercontent.com/u/22726660?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/xinxin12345",
            "html_url": "https://github.com/xinxin12345",
            "followers_url": "https://api.github.com/users/xinxin12345/followers",
            "following_url": "https://api.github.com/users/xinxin12345/following{/other_user}",
            "gists_url": "https://api.github.com/users/xinxin12345/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/xinxin12345/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/xinxin12345/subscriptions",
            "organizations_url": "https://api.github.com/users/xinxin12345/orgs",
            "repos_url": "https://api.github.com/users/xinxin12345/repos",
            "events_url": "https://api.github.com/users/xinxin12345/events{/privacy}",
            "received_events_url": "https://api.github.com/users/xinxin12345/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-04-06T07:25:52Z",
        "updated_at": "2023-04-06T07:25:52Z",
        "author_association": "NONE",
        "body": "> > @wangxiyuan Hi, Sorry to bother again. After the decorator package installed, I successed to compile and install onnxruntime-cann. But still have some error while using cann provider in the onnxruntime。 The provider configuration is:\r\n> > ` providers = [ ('CANNExecutionProvider', { 'device_id': 1, 'max_opqueue_num': 10000, 'arena_extend_strategy': 'kNextPowerOfTwo', 'npu_mem_limit': 2 * 1024 * 1024 * 1024, 'do_copy_in_default_stream': True, }), ]`\r\n> > and the error info is: ![image](https://user-images.githubusercontent.com/3061079/215312628-9e95e20f-6fc0-49ce-a217-3a8c112ed96a.png)\r\n> > And the code works well while i change the provider to **CPUExecutionProvider**。\r\n> > Also the ascend log file under the directory \"ascend/debug\" details are: **plog/plog-xxx.log:** ![image](https://user-images.githubusercontent.com/3061079/215312788-bc742a94-26bd-4b3c-8484-da8b49cfc5cf.png)\r\n> > **device-0/device-xxx.log:** ![image](https://user-images.githubusercontent.com/3061079/215312750-f8d660f2-a00b-4273-8460-2880059a7f30.png)\r\n> \r\n> So sorry for that.\r\n> \r\n> Can you refer to the [link](https://onnxruntime.ai/docs/execution-providers/community-maintained/CANN-ExecutionProvider.html#python) and try again? Pay attention to the `providers` field, please.\r\n> \r\n> If there are still errors, please enable debug log of Ascend and mail the log to `ljw1101.vip@gmail.com`.\r\n> \r\n> Thank you\r\n\r\n\"Have you solved this problem? I encountered the same issue when testing with the Python interface. The model works fine with CPU but raises errors when using the CANN backend.\"",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1498611012/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1498628872",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/14121#issuecomment-1498628872",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/14121",
        "id": 1498628872,
        "node_id": "IC_kwDOCVq1mM5ZU0MI",
        "user": {
            "login": "luoyangen",
            "id": 3061079,
            "node_id": "MDQ6VXNlcjMwNjEwNzk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3061079?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/luoyangen",
            "html_url": "https://github.com/luoyangen",
            "followers_url": "https://api.github.com/users/luoyangen/followers",
            "following_url": "https://api.github.com/users/luoyangen/following{/other_user}",
            "gists_url": "https://api.github.com/users/luoyangen/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/luoyangen/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/luoyangen/subscriptions",
            "organizations_url": "https://api.github.com/users/luoyangen/orgs",
            "repos_url": "https://api.github.com/users/luoyangen/repos",
            "events_url": "https://api.github.com/users/luoyangen/events{/privacy}",
            "received_events_url": "https://api.github.com/users/luoyangen/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-04-06T07:44:00Z",
        "updated_at": "2023-04-06T07:44:00Z",
        "author_association": "NONE",
        "body": "> > > @wangxiyuan Hi, Sorry to bother again. After the decorator package installed, I successed to compile and install onnxruntime-cann. But still have some error while using cann provider in the onnxruntime。 The provider configuration is:\r\n> > > ` providers = [ ('CANNExecutionProvider', { 'device_id': 1, 'max_opqueue_num': 10000, 'arena_extend_strategy': 'kNextPowerOfTwo', 'npu_mem_limit': 2 * 1024 * 1024 * 1024, 'do_copy_in_default_stream': True, }), ]`\r\n> > > and the error info is: ![image](https://user-images.githubusercontent.com/3061079/215312628-9e95e20f-6fc0-49ce-a217-3a8c112ed96a.png)\r\n> > > And the code works well while i change the provider to **CPUExecutionProvider**。\r\n> > > Also the ascend log file under the directory \"ascend/debug\" details are: **plog/plog-xxx.log:** ![image](https://user-images.githubusercontent.com/3061079/215312788-bc742a94-26bd-4b3c-8484-da8b49cfc5cf.png)\r\n> > > **device-0/device-xxx.log:** ![image](https://user-images.githubusercontent.com/3061079/215312750-f8d660f2-a00b-4273-8460-2880059a7f30.png)\r\n> > \r\n> > \r\n> > So sorry for that.\r\n> > Can you refer to the [link](https://onnxruntime.ai/docs/execution-providers/community-maintained/CANN-ExecutionProvider.html#python) and try again? Pay attention to the `providers` field, please.\r\n> > If there are still errors, please enable debug log of Ascend and mail the log to `ljw1101.vip@gmail.com`.\r\n> > Thank you\r\n> \r\n> \"Have you solved this problem? I encountered the same issue when testing with the Python interface. The model works fine with CPU but raises errors when using the CANN backend.\"\r\n\r\nMy model works now under the help of HUAWEI engineers. It was because one operator of my model was not supported by CANN. ",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1498628872/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1498639161",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/14121#issuecomment-1498639161",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/14121",
        "id": 1498639161,
        "node_id": "IC_kwDOCVq1mM5ZU2s5",
        "user": {
            "login": "xinxin12345",
            "id": 22726660,
            "node_id": "MDQ6VXNlcjIyNzI2NjYw",
            "avatar_url": "https://avatars.githubusercontent.com/u/22726660?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/xinxin12345",
            "html_url": "https://github.com/xinxin12345",
            "followers_url": "https://api.github.com/users/xinxin12345/followers",
            "following_url": "https://api.github.com/users/xinxin12345/following{/other_user}",
            "gists_url": "https://api.github.com/users/xinxin12345/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/xinxin12345/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/xinxin12345/subscriptions",
            "organizations_url": "https://api.github.com/users/xinxin12345/orgs",
            "repos_url": "https://api.github.com/users/xinxin12345/repos",
            "events_url": "https://api.github.com/users/xinxin12345/events{/privacy}",
            "received_events_url": "https://api.github.com/users/xinxin12345/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-04-06T07:53:08Z",
        "updated_at": "2023-04-06T07:53:08Z",
        "author_association": "NONE",
        "body": "> > > > @wangxiyuan Hi, Sorry to bother again. After the decorator package installed, I successed to compile and install onnxruntime-cann. But still have some error while using cann provider in the onnxruntime。 The provider configuration is:\r\n> > > > ` providers = [ ('CANNExecutionProvider', { 'device_id': 1, 'max_opqueue_num': 10000, 'arena_extend_strategy': 'kNextPowerOfTwo', 'npu_mem_limit': 2 * 1024 * 1024 * 1024, 'do_copy_in_default_stream': True, }), ]`\r\n> > > > and the error info is: ![image](https://user-images.githubusercontent.com/3061079/215312628-9e95e20f-6fc0-49ce-a217-3a8c112ed96a.png)\r\n> > > > And the code works well while i change the provider to **CPUExecutionProvider**。\r\n> > > > Also the ascend log file under the directory \"ascend/debug\" details are: **plog/plog-xxx.log:** ![image](https://user-images.githubusercontent.com/3061079/215312788-bc742a94-26bd-4b3c-8484-da8b49cfc5cf.png)\r\n> > > > **device-0/device-xxx.log:** ![image](https://user-images.githubusercontent.com/3061079/215312750-f8d660f2-a00b-4273-8460-2880059a7f30.png)\r\n> > > \r\n> > > \r\n> > > So sorry for that.\r\n> > > Can you refer to the [link](https://onnxruntime.ai/docs/execution-providers/community-maintained/CANN-ExecutionProvider.html#python) and try again? Pay attention to the `providers` field, please.\r\n> > > If there are still errors, please enable debug log of Ascend and mail the log to `ljw1101.vip@gmail.com`.\r\n> > > Thank you\r\n> > \r\n> > \r\n> > \"Have you solved this problem? I encountered the same issue when testing with the Python interface. The model works fine with CPU but raises errors when using the CANN backend.\"\r\n> \r\n> My model works now under the help of HUAWEI engineers. It was because one operator of my model was not supported by CANN.\r\n\r\n\"May I know if you contacted Huawei engineers through this email ljw1101.vip@gmail.com?\"",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1498639161/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1560416767",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/14121#issuecomment-1560416767",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/14121",
        "id": 1560416767,
        "node_id": "IC_kwDOCVq1mM5dAhH_",
        "user": {
            "login": "wangxiyuan",
            "id": 10891919,
            "node_id": "MDQ6VXNlcjEwODkxOTE5",
            "avatar_url": "https://avatars.githubusercontent.com/u/10891919?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/wangxiyuan",
            "html_url": "https://github.com/wangxiyuan",
            "followers_url": "https://api.github.com/users/wangxiyuan/followers",
            "following_url": "https://api.github.com/users/wangxiyuan/following{/other_user}",
            "gists_url": "https://api.github.com/users/wangxiyuan/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/wangxiyuan/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/wangxiyuan/subscriptions",
            "organizations_url": "https://api.github.com/users/wangxiyuan/orgs",
            "repos_url": "https://api.github.com/users/wangxiyuan/repos",
            "events_url": "https://api.github.com/users/wangxiyuan/events{/privacy}",
            "received_events_url": "https://api.github.com/users/wangxiyuan/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-05-24T03:44:22Z",
        "updated_at": "2023-05-24T03:44:56Z",
        "author_association": "CONTRIBUTOR",
        "body": "> > > > > @wangxiyuan Hi, Sorry to bother again. After the decorator package installed, I successed to compile and install onnxruntime-cann. But still have some error while using cann provider in the onnxruntime。 The provider configuration is:\r\n> > > > > ` providers = [ ('CANNExecutionProvider', { 'device_id': 1, 'max_opqueue_num': 10000, 'arena_extend_strategy': 'kNextPowerOfTwo', 'npu_mem_limit': 2 * 1024 * 1024 * 1024, 'do_copy_in_default_stream': True, }), ]`\r\n> > > > > and the error info is: ![image](https://user-images.githubusercontent.com/3061079/215312628-9e95e20f-6fc0-49ce-a217-3a8c112ed96a.png)\r\n> > > > > And the code works well while i change the provider to **CPUExecutionProvider**。\r\n> > > > > Also the ascend log file under the directory \"ascend/debug\" details are: **plog/plog-xxx.log:** ![image](https://user-images.githubusercontent.com/3061079/215312788-bc742a94-26bd-4b3c-8484-da8b49cfc5cf.png)\r\n> > > > > **device-0/device-xxx.log:** ![image](https://user-images.githubusercontent.com/3061079/215312750-f8d660f2-a00b-4273-8460-2880059a7f30.png)\r\n> > > > \r\n> > > > \r\n> > > > So sorry for that.\r\n> > > > Can you refer to the [link](https://onnxruntime.ai/docs/execution-providers/community-maintained/CANN-ExecutionProvider.html#python) and try again? Pay attention to the `providers` field, please.\r\n> > > > If there are still errors, please enable debug log of Ascend and mail the log to `ljw1101.vip@gmail.com`.\r\n> > > > Thank you\r\n> > > \r\n> > > \r\n> > > \"Have you solved this problem? I encountered the same issue when testing with the Python interface. The model works fine with CPU but raises errors when using the CANN backend.\"\r\n> > \r\n> > \r\n> > My model works now under the help of HUAWEI engineers. It was because one operator of my model was not supported by CANN.\r\n> \r\n> \"May I know if you contacted Huawei engineers through this email [ljw1101.vip@gmail.com](mailto:ljw1101.vip@gmail.com)?\"\r\n\r\n@xinxin12345 Hi, sorry that we missed the message for such a long time. Yes, you can send your problem to ljw1101.vip@gmail.com or wangxiyuan1007@gmail.com directly. Or describe it here. ",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1560416767/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]