[
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1224172241",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/12679#issuecomment-1224172241",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/12679",
        "id": 1224172241,
        "node_id": "IC_kwDOCVq1mM5I92LR",
        "user": {
            "login": "Craigacp",
            "id": 729696,
            "node_id": "MDQ6VXNlcjcyOTY5Ng==",
            "avatar_url": "https://avatars.githubusercontent.com/u/729696?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Craigacp",
            "html_url": "https://github.com/Craigacp",
            "followers_url": "https://api.github.com/users/Craigacp/followers",
            "following_url": "https://api.github.com/users/Craigacp/following{/other_user}",
            "gists_url": "https://api.github.com/users/Craigacp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Craigacp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Craigacp/subscriptions",
            "organizations_url": "https://api.github.com/users/Craigacp/orgs",
            "repos_url": "https://api.github.com/users/Craigacp/repos",
            "events_url": "https://api.github.com/users/Craigacp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Craigacp/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-08-23T14:40:21Z",
        "updated_at": "2022-08-23T14:40:34Z",
        "author_association": "CONTRIBUTOR",
        "body": "I've been working on a series of fixes for exception handling in the JNI code to deal with some crashes seen in Android & React-native (#11451), the last one is out for PR here - https://github.com/microsoft/onnxruntime/pull/12516. Can you build that branch and see if it fixes your issue?",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1224172241/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1226726748",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/12679#issuecomment-1226726748",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/12679",
        "id": 1226726748,
        "node_id": "IC_kwDOCVq1mM5JHl1c",
        "user": {
            "login": "Archie-eng",
            "id": 4669420,
            "node_id": "MDQ6VXNlcjQ2Njk0MjA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/4669420?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Archie-eng",
            "html_url": "https://github.com/Archie-eng",
            "followers_url": "https://api.github.com/users/Archie-eng/followers",
            "following_url": "https://api.github.com/users/Archie-eng/following{/other_user}",
            "gists_url": "https://api.github.com/users/Archie-eng/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Archie-eng/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Archie-eng/subscriptions",
            "organizations_url": "https://api.github.com/users/Archie-eng/orgs",
            "repos_url": "https://api.github.com/users/Archie-eng/repos",
            "events_url": "https://api.github.com/users/Archie-eng/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Archie-eng/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-08-25T03:25:34Z",
        "updated_at": "2022-08-25T03:25:34Z",
        "author_association": "NONE",
        "body": "I rebuilt Craigacap/onnxruntime, and android phone crashed irregularly.\r\n```\r\ngit clone --recursive https://github.com/Craigacp/onnxruntime\r\ngit checkout jni-util-refactor\r\nbuild.bat --android --android_sdk_path D:\\Android_SDK --android_ndk_path D:\\Android_SDK\\ndk\\23.0.7599858 --android_abi arm64-v8a --android_api 30 --cmake_generator Ninja   --build_java\r\n```\r\n\r\nlog info:\r\n```\r\n08-24 22:23:19.613 29309 29309 F DEBUG   : tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)\r\n08-24 22:23:19.613 29309 29309 F DEBUG   : pac_enabled_keys: 000000000000000f (PR_PAC_APIAKEY, PR_PAC_APIBKEY, PR_PAC_APDAKEY, PR_PAC_APDBKEY)\r\n08-24 22:23:19.613 29309 29309 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xb400006ec740024c\r\n08-24 22:23:19.613 29309 29309 F DEBUG   :     x0  b400006f35c7bba0  x1  b400006ec0f4e340  x2  b400006ec73fd000  x3  0000007ffb59d848\r\n08-24 22:23:19.613 29309 29309 F DEBUG   :     x4  b400006ec35f3680  x5  0000007ffb59dc58  x6  0000000000000000  x7  0000000000000001\r\n08-24 22:23:19.613 29309 29309 F DEBUG   :     x8  b400006ec73fd000  x9  0000000000000c93  x10 0000006ed853c2d0  x11 0000000000000000\r\n08-24 22:23:19.613 29309 29309 F DEBUG   :     x12 0000006f6180d7c0  x13 00000000000063c0  x14 000000000000000d  x15 0000000000000000\r\n08-24 22:23:19.613 29309 29309 F DEBUG   :     x16 0000006fe8f4e900  x17 0000006fe8f3e69c  x18 0000007002c16000  x19 b400006f61810800\r\n08-24 22:23:19.613 29309 29309 F DEBUG   :     x20 0000000000000000  x21 0000000000000000  x22 0000000012d014d0  x23 0000000012d000a8\r\n08-24 22:23:19.613 29309 29309 F DEBUG   :     x24 0000000000000002  x25 0000000000000000  x26 0000000012d00498  x27 0000000012d01528\r\n08-24 22:23:19.613 29309 29309 F DEBUG   :     x28 0000007ffb5a1570  x29 0000007ffb59d380\r\n08-24 22:23:19.613 29309 29309 F DEBUG   :     lr  0000006ed9489a1c  sp  0000007ffb59d2b0  pc  0000006ed94475c0  pst 0000000080001000\r\n08-24 22:23:19.613 29309 29309 F DEBUG   : backtrace:\r\n08-24 22:23:19.613 29309 29309 F DEBUG   :       #00 pc 000000000123f5c0  /data/app/~~WeJH_OCRA0gdIaVn8NYd7Q==/com.example.onnxdemo-Mnf8V_mTEpWATuh6DYj-Lw==/base.apk!libonnxruntime.so (BuildId: 456ae97cf247c7438941b5440ca8e35a4d8d5d65)\r\n```\r\n\r\nanalysis:\r\nMaybe there is something exception in tree_ensemble algo. I will try to debug further.\r\n```\r\n$addr2line -f -e libonnxruntime.so 000000000123f5c0\r\n_ZNK11onnxruntime2ml6detail18TreeEnsembleCommonIfffE20ProcessTreeNodeLeaveEPNS1_15TreeNodeElementIfEEPKf\r\nE:\\onnx\\craigacp\\onnxruntime\\build\\Windows\\Debug/E:/onnx/craigacp/onnxruntime/onnxruntime/core/providers/cpu/ml/tree_ensemble_common.h:572\r\n```",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1226726748/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1227019871",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/12679#issuecomment-1227019871",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/12679",
        "id": 1227019871,
        "node_id": "IC_kwDOCVq1mM5JItZf",
        "user": {
            "login": "Craigacp",
            "id": 729696,
            "node_id": "MDQ6VXNlcjcyOTY5Ng==",
            "avatar_url": "https://avatars.githubusercontent.com/u/729696?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Craigacp",
            "html_url": "https://github.com/Craigacp",
            "followers_url": "https://api.github.com/users/Craigacp/followers",
            "following_url": "https://api.github.com/users/Craigacp/following{/other_user}",
            "gists_url": "https://api.github.com/users/Craigacp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Craigacp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Craigacp/subscriptions",
            "organizations_url": "https://api.github.com/users/Craigacp/orgs",
            "repos_url": "https://api.github.com/users/Craigacp/repos",
            "events_url": "https://api.github.com/users/Craigacp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Craigacp/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-08-25T09:33:25Z",
        "updated_at": "2022-08-25T09:33:25Z",
        "author_association": "CONTRIBUTOR",
        "body": "Ok, if it's dying that deep inside ORT it is less likely to be a java side issue. Maybe there's something odd about the threading on Android?",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1227019871/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1229649131",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/12679#issuecomment-1229649131",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/12679",
        "id": 1229649131,
        "node_id": "IC_kwDOCVq1mM5JSvTr",
        "user": {
            "login": "Archie-eng",
            "id": 4669420,
            "node_id": "MDQ6VXNlcjQ2Njk0MjA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/4669420?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Archie-eng",
            "html_url": "https://github.com/Archie-eng",
            "followers_url": "https://api.github.com/users/Archie-eng/followers",
            "following_url": "https://api.github.com/users/Archie-eng/following{/other_user}",
            "gists_url": "https://api.github.com/users/Archie-eng/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Archie-eng/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Archie-eng/subscriptions",
            "organizations_url": "https://api.github.com/users/Archie-eng/orgs",
            "repos_url": "https://api.github.com/users/Archie-eng/repos",
            "events_url": "https://api.github.com/users/Archie-eng/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Archie-eng/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-08-29T01:50:19Z",
        "updated_at": "2022-08-29T01:50:19Z",
        "author_association": "NONE",
        "body": "> Ok, if it's dying that deep inside ORT it is less likely to be a java side issue. Maybe there's something odd about the threading on Android?\r\n\r\nCould you check ensemble algo？ Thanks.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1229649131/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1232383444",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/12679#issuecomment-1232383444",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/12679",
        "id": 1232383444,
        "node_id": "IC_kwDOCVq1mM5JdK3U",
        "user": {
            "login": "skottmckay",
            "id": 979079,
            "node_id": "MDQ6VXNlcjk3OTA3OQ==",
            "avatar_url": "https://avatars.githubusercontent.com/u/979079?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/skottmckay",
            "html_url": "https://github.com/skottmckay",
            "followers_url": "https://api.github.com/users/skottmckay/followers",
            "following_url": "https://api.github.com/users/skottmckay/following{/other_user}",
            "gists_url": "https://api.github.com/users/skottmckay/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/skottmckay/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/skottmckay/subscriptions",
            "organizations_url": "https://api.github.com/users/skottmckay/orgs",
            "repos_url": "https://api.github.com/users/skottmckay/repos",
            "events_url": "https://api.github.com/users/skottmckay/events{/privacy}",
            "received_events_url": "https://api.github.com/users/skottmckay/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-08-31T02:39:30Z",
        "updated_at": "2022-08-31T02:39:30Z",
        "author_association": "MEMBER",
        "body": "Not sure if it's a factor here, but ideally you should create the inference session once and re-use it. Loading the model is an expensive operation so the session is designed for re-use. You can call `run` as many times as you want, including concurrently.\r\n\r\n@xadupre any idea what could go wrong at onnxruntime/core/providers/cpu/ml/tree_ensemble_common.h:572?",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1232383444/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1232594503",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/12679#issuecomment-1232594503",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/12679",
        "id": 1232594503,
        "node_id": "IC_kwDOCVq1mM5Jd-ZH",
        "user": {
            "login": "Archie-eng",
            "id": 4669420,
            "node_id": "MDQ6VXNlcjQ2Njk0MjA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/4669420?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Archie-eng",
            "html_url": "https://github.com/Archie-eng",
            "followers_url": "https://api.github.com/users/Archie-eng/followers",
            "following_url": "https://api.github.com/users/Archie-eng/following{/other_user}",
            "gists_url": "https://api.github.com/users/Archie-eng/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Archie-eng/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Archie-eng/subscriptions",
            "organizations_url": "https://api.github.com/users/Archie-eng/orgs",
            "repos_url": "https://api.github.com/users/Archie-eng/repos",
            "events_url": "https://api.github.com/users/Archie-eng/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Archie-eng/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-08-31T07:57:53Z",
        "updated_at": "2022-08-31T07:57:53Z",
        "author_association": "NONE",
        "body": "> \r\n\r\nHi，my project has many models,  it needs to load different models to complete special feature.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1232594503/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1232604109",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/12679#issuecomment-1232604109",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/12679",
        "id": 1232604109,
        "node_id": "IC_kwDOCVq1mM5JeAvN",
        "user": {
            "login": "skottmckay",
            "id": 979079,
            "node_id": "MDQ6VXNlcjk3OTA3OQ==",
            "avatar_url": "https://avatars.githubusercontent.com/u/979079?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/skottmckay",
            "html_url": "https://github.com/skottmckay",
            "followers_url": "https://api.github.com/users/skottmckay/followers",
            "following_url": "https://api.github.com/users/skottmckay/following{/other_user}",
            "gists_url": "https://api.github.com/users/skottmckay/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/skottmckay/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/skottmckay/subscriptions",
            "organizations_url": "https://api.github.com/users/skottmckay/orgs",
            "repos_url": "https://api.github.com/users/skottmckay/repos",
            "events_url": "https://api.github.com/users/skottmckay/events{/privacy}",
            "received_events_url": "https://api.github.com/users/skottmckay/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-08-31T08:05:31Z",
        "updated_at": "2022-08-31T08:05:31Z",
        "author_association": "MEMBER",
        "body": "Is it crashing with a particular model? If so, are you able to share that model?\r\n\r\nIs the crash deterministic (same input will always make it crash)? I know you said it crashes irregularly, but it's not clear from that statement whether the input that made it crash would do the same if repeated.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1232604109/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1232640627",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/12679#issuecomment-1232640627",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/12679",
        "id": 1232640627,
        "node_id": "IC_kwDOCVq1mM5JeJpz",
        "user": {
            "login": "xadupre",
            "id": 22452781,
            "node_id": "MDQ6VXNlcjIyNDUyNzgx",
            "avatar_url": "https://avatars.githubusercontent.com/u/22452781?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/xadupre",
            "html_url": "https://github.com/xadupre",
            "followers_url": "https://api.github.com/users/xadupre/followers",
            "following_url": "https://api.github.com/users/xadupre/following{/other_user}",
            "gists_url": "https://api.github.com/users/xadupre/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/xadupre/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/xadupre/subscriptions",
            "organizations_url": "https://api.github.com/users/xadupre/orgs",
            "repos_url": "https://api.github.com/users/xadupre/repos",
            "events_url": "https://api.github.com/users/xadupre/events{/privacy}",
            "received_events_url": "https://api.github.com/users/xadupre/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-08-31T08:38:02Z",
        "updated_at": "2022-08-31T08:38:02Z",
        "author_association": "MEMBER",
        "body": "The mentioned line is `val = x_data[root->feature_id];`. It could crash if pointer `root` is wrong or pointer `x_data` is wrong or `root->feature_id` is an unexpected index. Pointer `root` seems to be ok since if went through the previous line. Pointer `x_data` comes from `const InputType* x_data = X->Data<InputType>();`. It should be ok too. That leaves the index. So maybe pointer `root` is wrong and `root->feature_id` returns a random integer. Or `root->feature_id` is either negative, either superior to the number higher than the number of features. \r\n\r\nNow here is a bigger snippet. Is it possible than one `root->is_not_leaf` is true when it should be false? onnxruntime does not check every path in the tree ends with a leaf. Maybe we should enforce that.\r\n\r\n```c\r\n          while (root->is_not_leaf) {\r\n            val = x_data[root->feature_id];   // fails here\r\n            root = val <= root->value ? root->truenode : root->falsenode;\r\n          }\r\n```\r\n\r\nIt would be great to have access the onnx model and which converting library generated it. Short term, I could add more code to check that every path has a leaf. I don't think that would add much to the loading time. It would be another pass on the whole tree structure.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1232640627/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1234428136",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/12679#issuecomment-1234428136",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/12679",
        "id": 1234428136,
        "node_id": "IC_kwDOCVq1mM5Jk-Do",
        "user": {
            "login": "Archie-eng",
            "id": 4669420,
            "node_id": "MDQ6VXNlcjQ2Njk0MjA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/4669420?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Archie-eng",
            "html_url": "https://github.com/Archie-eng",
            "followers_url": "https://api.github.com/users/Archie-eng/followers",
            "following_url": "https://api.github.com/users/Archie-eng/following{/other_user}",
            "gists_url": "https://api.github.com/users/Archie-eng/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Archie-eng/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Archie-eng/subscriptions",
            "organizations_url": "https://api.github.com/users/Archie-eng/orgs",
            "repos_url": "https://api.github.com/users/Archie-eng/repos",
            "events_url": "https://api.github.com/users/Archie-eng/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Archie-eng/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-09-01T15:19:07Z",
        "updated_at": "2022-09-01T15:19:07Z",
        "author_association": "NONE",
        "body": "> The mentioned line is `val = x_data[root->feature_id];`. It could crash if pointer `root` is wrong or pointer `x_data` is wrong or `root->feature_id` is an unexpected index. Pointer `root` seems to be ok since if went through the previous line. Pointer `x_data` comes from `const InputType* x_data = X->Data<InputType>();`. It should be ok too. That leaves the index. So maybe pointer `root` is wrong and `root->feature_id` returns a random integer. Or `root->feature_id` is either negative, either superior to the number higher than the number of features.\r\n> \r\n> Now here is a bigger snippet. Is it possible than one `root->is_not_leaf` is true when it should be false? onnxruntime does not check every path in the tree ends with a leaf. Maybe we should enforce that.\r\n> \r\n> ```c\r\n>           while (root->is_not_leaf) {\r\n>             val = x_data[root->feature_id];   // fails here\r\n>             root = val <= root->value ? root->truenode : root->falsenode;\r\n>           }\r\n> ```\r\n> \r\n> It would be great to have access the onnx model and which converting library generated it. Short term, I could add more code to check that every path has a leaf. I don't think that would add much to the loading time. It would be another pass on the whole tree structure.\r\n\r\nI upload the demo to OneDrive, please see https://1drv.ms/u/s!AlIiJbF2ZUwIa4xMyn_4k1DdPzg?e=j0n39j",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1234428136/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1234576053",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/12679#issuecomment-1234576053",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/12679",
        "id": 1234576053,
        "node_id": "IC_kwDOCVq1mM5JliK1",
        "user": {
            "login": "xadupre",
            "id": 22452781,
            "node_id": "MDQ6VXNlcjIyNDUyNzgx",
            "avatar_url": "https://avatars.githubusercontent.com/u/22452781?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/xadupre",
            "html_url": "https://github.com/xadupre",
            "followers_url": "https://api.github.com/users/xadupre/followers",
            "following_url": "https://api.github.com/users/xadupre/following{/other_user}",
            "gists_url": "https://api.github.com/users/xadupre/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/xadupre/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/xadupre/subscriptions",
            "organizations_url": "https://api.github.com/users/xadupre/orgs",
            "repos_url": "https://api.github.com/users/xadupre/repos",
            "events_url": "https://api.github.com/users/xadupre/events{/privacy}",
            "received_events_url": "https://api.github.com/users/xadupre/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-09-01T17:29:14Z",
        "updated_at": "2022-09-01T17:29:32Z",
        "author_association": "MEMBER",
        "body": "I looked into your file. I found a couple of models `*.ort` and two datasets (`input*.csv`). The smallest one works for me (in python). The second dataset has only one line and the number of values is not a multiple of the number of columns of the first one. Is it possible to know which combination of model and dataset fails?",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1234576053/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1234993174",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/12679#issuecomment-1234993174",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/12679",
        "id": 1234993174,
        "node_id": "IC_kwDOCVq1mM5JnIAW",
        "user": {
            "login": "Archie-eng",
            "id": 4669420,
            "node_id": "MDQ6VXNlcjQ2Njk0MjA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/4669420?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Archie-eng",
            "html_url": "https://github.com/Archie-eng",
            "followers_url": "https://api.github.com/users/Archie-eng/followers",
            "following_url": "https://api.github.com/users/Archie-eng/following{/other_user}",
            "gists_url": "https://api.github.com/users/Archie-eng/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Archie-eng/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Archie-eng/subscriptions",
            "organizations_url": "https://api.github.com/users/Archie-eng/orgs",
            "repos_url": "https://api.github.com/users/Archie-eng/repos",
            "events_url": "https://api.github.com/users/Archie-eng/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Archie-eng/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-09-02T02:19:17Z",
        "updated_at": "2022-09-02T02:19:17Z",
        "author_association": "NONE",
        "body": "> I looked into your file. I found a couple of models `*.ort` and two datasets (`input*.csv`). The smallest one works for me (in python). The second dataset has only one line and the number of values is not a multiple of the number of columns of the first one. Is it possible to know which combination of model and dataset fails?\r\n\r\nI used input.csv which has six sets of input data, meanwhile  I used six models(model_*.ort) to inference.\r\nMap table:\r\ninput data           model\r\nline 1            ->   model_7.ort\r\nline 2            ->   model_8.ort\r\nline 3            ->   model_9.ort\r\nline 4            ->   model_10.ort\r\nline 5            ->   model_12.ort\r\nline 6            ->   model_14.ort",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1234993174/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1235214491",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/12679#issuecomment-1235214491",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/12679",
        "id": 1235214491,
        "node_id": "IC_kwDOCVq1mM5Jn-Cb",
        "user": {
            "login": "skottmckay",
            "id": 979079,
            "node_id": "MDQ6VXNlcjk3OTA3OQ==",
            "avatar_url": "https://avatars.githubusercontent.com/u/979079?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/skottmckay",
            "html_url": "https://github.com/skottmckay",
            "followers_url": "https://api.github.com/users/skottmckay/followers",
            "following_url": "https://api.github.com/users/skottmckay/following{/other_user}",
            "gists_url": "https://api.github.com/users/skottmckay/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/skottmckay/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/skottmckay/subscriptions",
            "organizations_url": "https://api.github.com/users/skottmckay/orgs",
            "repos_url": "https://api.github.com/users/skottmckay/repos",
            "events_url": "https://api.github.com/users/skottmckay/events{/privacy}",
            "received_events_url": "https://api.github.com/users/skottmckay/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-09-02T08:20:34Z",
        "updated_at": "2022-09-02T08:25:22Z",
        "author_association": "MEMBER",
        "body": "There's definitely a random crash and this isn't Android specific. Reproducible on Windows via python. Sometimes the below script runs to completion. Sometimes it dies on the first model. Most often on the second.\r\n\r\nAdjust paths as necessary. I moved the input.csv (onnxruntime_project\\app\\src\\main\\assets) and .ort models (onnxruntime_project\\app\\src\\main\\res\\raw) to the d:\\tmp\\ directory and used that in the script.\r\n\r\n```py\r\nimport csv\r\nimport numpy as np\r\nimport onnxruntime as ort\r\n\r\nmodel_base = r\"d:\\tmp\\model_\"\r\nmodels = [\"7.ort\",\r\n          \"8.ort\",\r\n          \"9.ort\",\r\n          \"10.ort\",\r\n          \"12.ort\",\r\n          \"14.ort\"]\r\n\r\nwith open(r\"d:\\tmp\\input.csv\") as csvfile:\r\n    r = csv.reader(csvfile)\r\n    idx = 0\r\n    for row in r:\r\n        model = model_base + models[idx]\r\n        s = ort.InferenceSession(model)\r\n        input = []\r\n        for item in row:\r\n            # trim 'f'. not sure why the input data has an 'f' if the processing has to ignore it.\r\n            input.append(float(item[:-1]))\r\n\r\n        n_input = np.array(input, dtype=np.float32)\r\n        n_input = np.expand_dims(n_input, 0)\r\n        print(n_input.shape)\r\n        print(model)\r\n        label = s.run(None, {'float_input': n_input})[0]\r\n        print(label)\r\n        idx += 1\r\n```",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1235214491/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1235743200",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/12679#issuecomment-1235743200",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/12679",
        "id": 1235743200,
        "node_id": "IC_kwDOCVq1mM5Jp_Hg",
        "user": {
            "login": "xadupre",
            "id": 22452781,
            "node_id": "MDQ6VXNlcjIyNDUyNzgx",
            "avatar_url": "https://avatars.githubusercontent.com/u/22452781?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/xadupre",
            "html_url": "https://github.com/xadupre",
            "followers_url": "https://api.github.com/users/xadupre/followers",
            "following_url": "https://api.github.com/users/xadupre/following{/other_user}",
            "gists_url": "https://api.github.com/users/xadupre/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/xadupre/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/xadupre/subscriptions",
            "organizations_url": "https://api.github.com/users/xadupre/orgs",
            "repos_url": "https://api.github.com/users/xadupre/repos",
            "events_url": "https://api.github.com/users/xadupre/events{/privacy}",
            "received_events_url": "https://api.github.com/users/xadupre/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-09-02T17:22:44Z",
        "updated_at": "2022-09-02T17:23:09Z",
        "author_association": "MEMBER",
        "body": "@skottmckay I'll look into that on Monday. Your script never fails for me on Windows. What version of python did you use and which distribution (Anaconda, miniconda, ...)? Another question, when I try to load the model with onnx.load, I get an error message. Is it expected?",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1235743200/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1237172344",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/12679#issuecomment-1237172344",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/12679",
        "id": 1237172344,
        "node_id": "IC_kwDOCVq1mM5JvcB4",
        "user": {
            "login": "xadupre",
            "id": 22452781,
            "node_id": "MDQ6VXNlcjIyNDUyNzgx",
            "avatar_url": "https://avatars.githubusercontent.com/u/22452781?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/xadupre",
            "html_url": "https://github.com/xadupre",
            "followers_url": "https://api.github.com/users/xadupre/followers",
            "following_url": "https://api.github.com/users/xadupre/following{/other_user}",
            "gists_url": "https://api.github.com/users/xadupre/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/xadupre/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/xadupre/subscriptions",
            "organizations_url": "https://api.github.com/users/xadupre/orgs",
            "repos_url": "https://api.github.com/users/xadupre/repos",
            "events_url": "https://api.github.com/users/xadupre/events{/privacy}",
            "received_events_url": "https://api.github.com/users/xadupre/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-09-05T15:00:33Z",
        "updated_at": "2022-09-05T15:00:33Z",
        "author_association": "MEMBER",
        "body": "I looked into the feature_ids in your model and I saw ``3219, 2760, 2252, 894, 2803, 3219, 1913, 0, 0, 2734, 2815, 1497, 241, 2107, 1547, 148, 91, 0, 91, 1397, 801, 0, 0, 0, 0, 3219, 2050, 0, 0, 0, 2770, 0, 0, 2107, 1397, 0, 0, 0, 811, 0, 0, 0, 0, 0, 0, 811, 3219, 158, 2853, 2853, 158, 0, 811, 0, 0, 0, 0, 158, 0, 894, 0, 1547, 811, 0...``. Most of them are above the number of columns of your input (245). I suspect your training input was sparse and your input data only contains the non null features. I'll add a test in the code to catch that issue. onnxruntime will still crash but with a proper exception. In your case, i'm wondering if my assumption is true: your test data is different from your train data (less features).",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1237172344/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1237493143",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/12679#issuecomment-1237493143",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/12679",
        "id": 1237493143,
        "node_id": "IC_kwDOCVq1mM5JwqWX",
        "user": {
            "login": "skottmckay",
            "id": 979079,
            "node_id": "MDQ6VXNlcjk3OTA3OQ==",
            "avatar_url": "https://avatars.githubusercontent.com/u/979079?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/skottmckay",
            "html_url": "https://github.com/skottmckay",
            "followers_url": "https://api.github.com/users/skottmckay/followers",
            "following_url": "https://api.github.com/users/skottmckay/following{/other_user}",
            "gists_url": "https://api.github.com/users/skottmckay/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/skottmckay/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/skottmckay/subscriptions",
            "organizations_url": "https://api.github.com/users/skottmckay/orgs",
            "repos_url": "https://api.github.com/users/skottmckay/repos",
            "events_url": "https://api.github.com/users/skottmckay/events{/privacy}",
            "received_events_url": "https://api.github.com/users/skottmckay/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-09-05T22:06:13Z",
        "updated_at": "2022-09-05T22:06:13Z",
        "author_association": "MEMBER",
        "body": "> Your script never fails for me on Windows. What version of python did you use and which distribution (Anaconda, miniconda, ...)? Another question, when I try to load the model with onnx.load, I get an error message. Is it expected?\r\n\r\nThey're ORT format models so 'onnx.load' won't work.\r\n\r\nUsing python 3.9 from python.org via PyCharm with ORT 1.12.1",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1237493143/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1237566680",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/12679#issuecomment-1237566680",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/12679",
        "id": 1237566680,
        "node_id": "IC_kwDOCVq1mM5Jw8TY",
        "user": {
            "login": "Archie-eng",
            "id": 4669420,
            "node_id": "MDQ6VXNlcjQ2Njk0MjA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/4669420?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Archie-eng",
            "html_url": "https://github.com/Archie-eng",
            "followers_url": "https://api.github.com/users/Archie-eng/followers",
            "following_url": "https://api.github.com/users/Archie-eng/following{/other_user}",
            "gists_url": "https://api.github.com/users/Archie-eng/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Archie-eng/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Archie-eng/subscriptions",
            "organizations_url": "https://api.github.com/users/Archie-eng/orgs",
            "repos_url": "https://api.github.com/users/Archie-eng/repos",
            "events_url": "https://api.github.com/users/Archie-eng/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Archie-eng/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-09-06T01:29:22Z",
        "updated_at": "2022-09-06T01:29:22Z",
        "author_association": "NONE",
        "body": "> I looked into the feature_ids in your model and I saw `3219, 2760, 2252, 894, 2803, 3219, 1913, 0, 0, 2734, 2815, 1497, 241, 2107, 1547, 148, 91, 0, 91, 1397, 801, 0, 0, 0, 0, 3219, 2050, 0, 0, 0, 2770, 0, 0, 2107, 1397, 0, 0, 0, 811, 0, 0, 0, 0, 0, 0, 811, 3219, 158, 2853, 2853, 158, 0, 811, 0, 0, 0, 0, 158, 0, 894, 0, 1547, 811, 0...`. Most of them are above the number of columns of your input (245). I suspect your training input was sparse and your input data only contains the non null features. I'll add a test in the code to catch that issue. onnxruntime will still crash but with a proper exception. In your case, i'm wondering if my assumption is true: your test data is different from your train data (less features).\r\n\r\nYes,  my test data has less features than training input in model. I will merge #12859 and retest again, thanks.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1237566680/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1238820231",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/12679#issuecomment-1238820231",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/12679",
        "id": 1238820231,
        "node_id": "IC_kwDOCVq1mM5J1uWH",
        "user": {
            "login": "Archie-eng",
            "id": 4669420,
            "node_id": "MDQ6VXNlcjQ2Njk0MjA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/4669420?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Archie-eng",
            "html_url": "https://github.com/Archie-eng",
            "followers_url": "https://api.github.com/users/Archie-eng/followers",
            "following_url": "https://api.github.com/users/Archie-eng/following{/other_user}",
            "gists_url": "https://api.github.com/users/Archie-eng/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Archie-eng/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Archie-eng/subscriptions",
            "organizations_url": "https://api.github.com/users/Archie-eng/orgs",
            "repos_url": "https://api.github.com/users/Archie-eng/repos",
            "events_url": "https://api.github.com/users/Archie-eng/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Archie-eng/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-09-07T01:55:57Z",
        "updated_at": "2022-09-07T01:55:57Z",
        "author_association": "NONE",
        "body": "> > I looked into the feature_ids in your model and I saw `3219, 2760, 2252, 894, 2803, 3219, 1913, 0, 0, 2734, 2815, 1497, 241, 2107, 1547, 148, 91, 0, 91, 1397, 801, 0, 0, 0, 0, 3219, 2050, 0, 0, 0, 2770, 0, 0, 2107, 1397, 0, 0, 0, 811, 0, 0, 0, 0, 0, 0, 811, 3219, 158, 2853, 2853, 158, 0, 811, 0, 0, 0, 0, 158, 0, 894, 0, 1547, 811, 0...`. Most of them are above the number of columns of your input (245). I suspect your training input was sparse and your input data only contains the non null features. I'll add a test in the code to catch that issue. onnxruntime will still crash but with a proper exception. In your case, i'm wondering if my assumption is true: your test data is different from your train data (less features).\r\n> \r\n> Yes, my test data has less features than training input in model. I will merge #12859 and retest again, thanks.\r\n\r\nNow, onnxruntime throw an exception as below.  Thanks for your support.\r\nError code - ORT_RUNTIME_EXCEPTION - message: Non-zero status code returned while running TreeEnsembleClassifier node. Name:'TreeEnsembleClassifier9' Status Message: E:/onnx/craigacp/onnxruntime/onnxruntime/core/providers/cpu/ml/tree_ensemble_common.h:359 void onnxruntime::ml::detail::TreeEnsembleCommon<float, float, float>::ComputeAgg(concurrency::ThreadPool *, const onnxruntime::Tensor *, onnxruntime::Tensor *, onnxruntime::Tensor *, const AGG &) const [InputType = float, ThresholdType = float, OutputType = float, AGG = onnxruntime::ml::detail::TreeAggregatorClassifier<float, float, float>] One path in the graph requests feature 4035 but input tensor has 245 features.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1238820231/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]