[
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1110915026",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/10894#issuecomment-1110915026",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/10894",
        "id": 1110915026,
        "node_id": "IC_kwDOCVq1mM5CNzfS",
        "user": {
            "login": "ephr4321",
            "id": 23211899,
            "node_id": "MDQ6VXNlcjIzMjExODk5",
            "avatar_url": "https://avatars.githubusercontent.com/u/23211899?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ephr4321",
            "html_url": "https://github.com/ephr4321",
            "followers_url": "https://api.github.com/users/ephr4321/followers",
            "following_url": "https://api.github.com/users/ephr4321/following{/other_user}",
            "gists_url": "https://api.github.com/users/ephr4321/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/ephr4321/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ephr4321/subscriptions",
            "organizations_url": "https://api.github.com/users/ephr4321/orgs",
            "repos_url": "https://api.github.com/users/ephr4321/repos",
            "events_url": "https://api.github.com/users/ephr4321/events{/privacy}",
            "received_events_url": "https://api.github.com/users/ephr4321/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-04-27T11:59:57Z",
        "updated_at": "2022-04-27T11:59:57Z",
        "author_association": "NONE",
        "body": "I had a similar problem when running about 12 different models. I got the error only at the 8th model, and saw I'm actually out of GPU memory...\r\nI see you have 12GB of Memory, but maybe...",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1110915026/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1202060015",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/10894#issuecomment-1202060015",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/10894",
        "id": 1202060015,
        "node_id": "IC_kwDOCVq1mM5Hpfrv",
        "user": {
            "login": "tall-josh",
            "id": 18511395,
            "node_id": "MDQ6VXNlcjE4NTExMzk1",
            "avatar_url": "https://avatars.githubusercontent.com/u/18511395?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/tall-josh",
            "html_url": "https://github.com/tall-josh",
            "followers_url": "https://api.github.com/users/tall-josh/followers",
            "following_url": "https://api.github.com/users/tall-josh/following{/other_user}",
            "gists_url": "https://api.github.com/users/tall-josh/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/tall-josh/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/tall-josh/subscriptions",
            "organizations_url": "https://api.github.com/users/tall-josh/orgs",
            "repos_url": "https://api.github.com/users/tall-josh/repos",
            "events_url": "https://api.github.com/users/tall-josh/events{/privacy}",
            "received_events_url": "https://api.github.com/users/tall-josh/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-08-02T06:11:32Z",
        "updated_at": "2022-08-31T01:18:05Z",
        "author_association": "NONE",
        "body": "I got a similar error:\r\n\r\n```console\r\nRuntimeError: Error in execution: Non-zero status code returned while running FusedConv node. Name:'Conv_0' Status Message: /onnxruntime_src/include/onnxruntime/core/framework/op_kernel_context.h:40 const T* onnxruntime::OpKernelContext::Input(int) const [with T = onnxruntime::Tensor] Missing Input: input\r\n```\r\n\r\nTurns out I was checking for Cuda availability before setting `io_binding` for my input. I only set the binding if Cuda was available but used `sess.run_with_iobinding(self.io_binding)` in both Cuda and CPU cases. The fix was to remove the conditional around the `bind_cpu_input`. ie:\r\n\r\n```python\r\n#### BAD ####\r\nif ort.get_device() == \"GPU\":\r\n    self.io_binding.bind_cpu_input(\"input\", preproc_crops)\r\nself.sess.run_with_iobinding(self.io_binding)\r\nort_outputs = self.io_binding.copy_outputs_to_cpu()\r\n#############\r\n\r\n#### GOOD ####\r\nself.io_binding.bind_cpu_input(\"input\", preproc_crops)\r\nself.sess.run_with_iobinding(self.io_binding)\r\nort_outputs = self.io_binding.copy_outputs_to_cpu()\r\n#############\r\n```\r\n\r\nIn the [docs](https://onnxruntime.ai/docs/api/python/api_summary.html#data-on-device) _that I only read as a last resort_ :-p it says `io_binding.bind_cpu_input('input', X)` will \"_copy the data over to the CUDA device **if** 'input' is consumed by nodes on the CUDA device_\". So if 'input' is not consumed by nodes of the CUDA device it will not do the copy, but 'input' will still be passed to the CPU. \r\n\r\nThe error in my original thinking was that the bind was only required **if** GPU was available but that meant the 'input' was not bound to any device in the case where GPU was not available.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1202060015/reactions",
            "total_count": 2,
            "+1": 2,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]