[
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1413203678",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/13572#issuecomment-1413203678",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/13572",
        "id": 1413203678,
        "node_id": "IC_kwDOCVq1mM5UO8be",
        "user": {
            "login": "Magnus1cheng",
            "id": 88537848,
            "node_id": "MDQ6VXNlcjg4NTM3ODQ4",
            "avatar_url": "https://avatars.githubusercontent.com/u/88537848?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Magnus1cheng",
            "html_url": "https://github.com/Magnus1cheng",
            "followers_url": "https://api.github.com/users/Magnus1cheng/followers",
            "following_url": "https://api.github.com/users/Magnus1cheng/following{/other_user}",
            "gists_url": "https://api.github.com/users/Magnus1cheng/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Magnus1cheng/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Magnus1cheng/subscriptions",
            "organizations_url": "https://api.github.com/users/Magnus1cheng/orgs",
            "repos_url": "https://api.github.com/users/Magnus1cheng/repos",
            "events_url": "https://api.github.com/users/Magnus1cheng/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Magnus1cheng/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-02-02T06:08:48Z",
        "updated_at": "2023-02-02T06:11:40Z",
        "author_association": "CONTRIBUTOR",
        "body": "I met same error message. I passed `--use_cuda`  and  `--enable_training`, and they caused https://github.com/microsoft/onnxruntime/blob/main/tools/ci_build/build.py#L1963 and https://github.com/microsoft/onnxruntime/blob/main/setup.py#L523, \r\nand eventually package_name  is not \"onnxruntime-tvm\":\r\nhttps://github.com/microsoft/onnxruntime/blob/main/setup.py#L597.\r\n\r\nI solved it by remove `--use_cuda` and `--enable_training` arguments. Not sure what caused your error. But basiclly, you need to make sure the package_name is \"onnxruntime-tvm\", which means code runs to https://github.com/microsoft/onnxruntime/blob/main/setup.py#L598.\r\n",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1413203678/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]