[
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1129201719",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11548#issuecomment-1129201719",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11548",
        "id": 1129201719,
        "node_id": "IC_kwDOCVq1mM5DTkA3",
        "user": {
            "login": "yuslepukhin",
            "id": 11303988,
            "node_id": "MDQ6VXNlcjExMzAzOTg4",
            "avatar_url": "https://avatars.githubusercontent.com/u/11303988?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/yuslepukhin",
            "html_url": "https://github.com/yuslepukhin",
            "followers_url": "https://api.github.com/users/yuslepukhin/followers",
            "following_url": "https://api.github.com/users/yuslepukhin/following{/other_user}",
            "gists_url": "https://api.github.com/users/yuslepukhin/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/yuslepukhin/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/yuslepukhin/subscriptions",
            "organizations_url": "https://api.github.com/users/yuslepukhin/orgs",
            "repos_url": "https://api.github.com/users/yuslepukhin/repos",
            "events_url": "https://api.github.com/users/yuslepukhin/events{/privacy}",
            "received_events_url": "https://api.github.com/users/yuslepukhin/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-05-17T18:45:17Z",
        "updated_at": "2022-05-17T18:45:17Z",
        "author_association": "MEMBER",
        "body": "It may be a bug. Try the latest ORT release, or share with us your model to investigate.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1129201719/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1129481857",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11548#issuecomment-1129481857",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11548",
        "id": 1129481857,
        "node_id": "IC_kwDOCVq1mM5DUoaB",
        "user": {
            "login": "pythondever",
            "id": 24561457,
            "node_id": "MDQ6VXNlcjI0NTYxNDU3",
            "avatar_url": "https://avatars.githubusercontent.com/u/24561457?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/pythondever",
            "html_url": "https://github.com/pythondever",
            "followers_url": "https://api.github.com/users/pythondever/followers",
            "following_url": "https://api.github.com/users/pythondever/following{/other_user}",
            "gists_url": "https://api.github.com/users/pythondever/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/pythondever/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/pythondever/subscriptions",
            "organizations_url": "https://api.github.com/users/pythondever/orgs",
            "repos_url": "https://api.github.com/users/pythondever/repos",
            "events_url": "https://api.github.com/users/pythondever/events{/privacy}",
            "received_events_url": "https://api.github.com/users/pythondever/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-05-18T01:46:00Z",
        "updated_at": "2022-05-18T01:46:00Z",
        "author_association": "NONE",
        "body": "> It may be a bug. Try the latest ORT release, or share with us your model to investigate.\r\n\r\nI've tried that，but it doesn't work",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1129481857/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1129498156",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11548#issuecomment-1129498156",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11548",
        "id": 1129498156,
        "node_id": "IC_kwDOCVq1mM5DUsYs",
        "user": {
            "login": "pythondever",
            "id": 24561457,
            "node_id": "MDQ6VXNlcjI0NTYxNDU3",
            "avatar_url": "https://avatars.githubusercontent.com/u/24561457?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/pythondever",
            "html_url": "https://github.com/pythondever",
            "followers_url": "https://api.github.com/users/pythondever/followers",
            "following_url": "https://api.github.com/users/pythondever/following{/other_user}",
            "gists_url": "https://api.github.com/users/pythondever/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/pythondever/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/pythondever/subscriptions",
            "organizations_url": "https://api.github.com/users/pythondever/orgs",
            "repos_url": "https://api.github.com/users/pythondever/repos",
            "events_url": "https://api.github.com/users/pythondever/events{/privacy}",
            "received_events_url": "https://api.github.com/users/pythondever/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-05-18T02:20:06Z",
        "updated_at": "2022-05-18T02:20:06Z",
        "author_association": "NONE",
        "body": "> It may be a bug. Try the latest ORT release, or share with us your model to investigate.\r\n\r\nmodel file [https://github.com/pythondever/_onnx_demo_error](url)",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1129498156/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1134738250",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11548#issuecomment-1134738250",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11548",
        "id": 1134738250,
        "node_id": "IC_kwDOCVq1mM5DortK",
        "user": {
            "login": "pythondever",
            "id": 24561457,
            "node_id": "MDQ6VXNlcjI0NTYxNDU3",
            "avatar_url": "https://avatars.githubusercontent.com/u/24561457?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/pythondever",
            "html_url": "https://github.com/pythondever",
            "followers_url": "https://api.github.com/users/pythondever/followers",
            "following_url": "https://api.github.com/users/pythondever/following{/other_user}",
            "gists_url": "https://api.github.com/users/pythondever/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/pythondever/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/pythondever/subscriptions",
            "organizations_url": "https://api.github.com/users/pythondever/orgs",
            "repos_url": "https://api.github.com/users/pythondever/repos",
            "events_url": "https://api.github.com/users/pythondever/events{/privacy}",
            "received_events_url": "https://api.github.com/users/pythondever/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-05-23T14:18:13Z",
        "updated_at": "2022-05-23T14:18:13Z",
        "author_association": "NONE",
        "body": "@yuslepukhin  Is there anything update？",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1134738250/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1136229588",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11548#issuecomment-1136229588",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11548",
        "id": 1136229588,
        "node_id": "IC_kwDOCVq1mM5DuXzU",
        "user": {
            "login": "yuslepukhin",
            "id": 11303988,
            "node_id": "MDQ6VXNlcjExMzAzOTg4",
            "avatar_url": "https://avatars.githubusercontent.com/u/11303988?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/yuslepukhin",
            "html_url": "https://github.com/yuslepukhin",
            "followers_url": "https://api.github.com/users/yuslepukhin/followers",
            "following_url": "https://api.github.com/users/yuslepukhin/following{/other_user}",
            "gists_url": "https://api.github.com/users/yuslepukhin/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/yuslepukhin/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/yuslepukhin/subscriptions",
            "organizations_url": "https://api.github.com/users/yuslepukhin/orgs",
            "repos_url": "https://api.github.com/users/yuslepukhin/repos",
            "events_url": "https://api.github.com/users/yuslepukhin/events{/privacy}",
            "received_events_url": "https://api.github.com/users/yuslepukhin/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-05-24T17:22:54Z",
        "updated_at": "2022-05-24T17:22:54Z",
        "author_association": "MEMBER",
        "body": "> @yuslepukhin Is there anything update？\r\n\r\nI did not get a chance to look at it yet.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1136229588/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1136625746",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11548#issuecomment-1136625746",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11548",
        "id": 1136625746,
        "node_id": "IC_kwDOCVq1mM5Dv4hS",
        "user": {
            "login": "beyonehan",
            "id": 19468927,
            "node_id": "MDQ6VXNlcjE5NDY4OTI3",
            "avatar_url": "https://avatars.githubusercontent.com/u/19468927?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/beyonehan",
            "html_url": "https://github.com/beyonehan",
            "followers_url": "https://api.github.com/users/beyonehan/followers",
            "following_url": "https://api.github.com/users/beyonehan/following{/other_user}",
            "gists_url": "https://api.github.com/users/beyonehan/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/beyonehan/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/beyonehan/subscriptions",
            "organizations_url": "https://api.github.com/users/beyonehan/orgs",
            "repos_url": "https://api.github.com/users/beyonehan/repos",
            "events_url": "https://api.github.com/users/beyonehan/events{/privacy}",
            "received_events_url": "https://api.github.com/users/beyonehan/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-05-25T01:54:46Z",
        "updated_at": "2022-05-25T01:57:23Z",
        "author_association": "NONE",
        "body": "> > @yuslepukhin Is there anything update？\r\n> \r\n> I did not get a chance to look at it yet.\r\n\r\nI have the same problem as well. I have tried everything I can do but still doesn't work. Could you give me some suggestions? Many thanks.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1136625746/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1137848213",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11548#issuecomment-1137848213",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11548",
        "id": 1137848213,
        "node_id": "IC_kwDOCVq1mM5D0i-V",
        "user": {
            "login": "yuslepukhin",
            "id": 11303988,
            "node_id": "MDQ6VXNlcjExMzAzOTg4",
            "avatar_url": "https://avatars.githubusercontent.com/u/11303988?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/yuslepukhin",
            "html_url": "https://github.com/yuslepukhin",
            "followers_url": "https://api.github.com/users/yuslepukhin/followers",
            "following_url": "https://api.github.com/users/yuslepukhin/following{/other_user}",
            "gists_url": "https://api.github.com/users/yuslepukhin/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/yuslepukhin/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/yuslepukhin/subscriptions",
            "organizations_url": "https://api.github.com/users/yuslepukhin/orgs",
            "repos_url": "https://api.github.com/users/yuslepukhin/repos",
            "events_url": "https://api.github.com/users/yuslepukhin/events{/privacy}",
            "received_events_url": "https://api.github.com/users/yuslepukhin/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-05-25T21:05:53Z",
        "updated_at": "2022-05-25T21:05:53Z",
        "author_association": "MEMBER",
        "body": "Please, follow the issue reporting template and submit a program that reproduces the behavior, that would speed up things a lot. Please, attach the input data and your model if you are able to. Then we would be able to determine what the issue is and the best course of action.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1137848213/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1138053981",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11548#issuecomment-1138053981",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11548",
        "id": 1138053981,
        "node_id": "IC_kwDOCVq1mM5D1VNd",
        "user": {
            "login": "pythondever",
            "id": 24561457,
            "node_id": "MDQ6VXNlcjI0NTYxNDU3",
            "avatar_url": "https://avatars.githubusercontent.com/u/24561457?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/pythondever",
            "html_url": "https://github.com/pythondever",
            "followers_url": "https://api.github.com/users/pythondever/followers",
            "following_url": "https://api.github.com/users/pythondever/following{/other_user}",
            "gists_url": "https://api.github.com/users/pythondever/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/pythondever/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/pythondever/subscriptions",
            "organizations_url": "https://api.github.com/users/pythondever/orgs",
            "repos_url": "https://api.github.com/users/pythondever/repos",
            "events_url": "https://api.github.com/users/pythondever/events{/privacy}",
            "received_events_url": "https://api.github.com/users/pythondever/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-05-26T01:45:12Z",
        "updated_at": "2022-05-26T01:45:12Z",
        "author_association": "NONE",
        "body": "@yuslepukhin thanks reply！\r\nI push my demo program please follow this url [https://github.com/pythondever/_onnx_demo_error](url)\r\nand just run python pred_onnx.py， you can reproduce the error",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1138053981/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1138874511",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11548#issuecomment-1138874511",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11548",
        "id": 1138874511,
        "node_id": "IC_kwDOCVq1mM5D4diP",
        "user": {
            "login": "yuslepukhin",
            "id": 11303988,
            "node_id": "MDQ6VXNlcjExMzAzOTg4",
            "avatar_url": "https://avatars.githubusercontent.com/u/11303988?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/yuslepukhin",
            "html_url": "https://github.com/yuslepukhin",
            "followers_url": "https://api.github.com/users/yuslepukhin/followers",
            "following_url": "https://api.github.com/users/yuslepukhin/following{/other_user}",
            "gists_url": "https://api.github.com/users/yuslepukhin/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/yuslepukhin/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/yuslepukhin/subscriptions",
            "organizations_url": "https://api.github.com/users/yuslepukhin/orgs",
            "repos_url": "https://api.github.com/users/yuslepukhin/repos",
            "events_url": "https://api.github.com/users/yuslepukhin/events{/privacy}",
            "received_events_url": "https://api.github.com/users/yuslepukhin/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-05-26T18:14:19Z",
        "updated_at": "2022-05-26T18:14:19Z",
        "author_association": "MEMBER",
        "body": "> @yuslepukhin thanks reply！ I push my demo program please follow this url [https://github.com/pythondever/_onnx_demo_error](url) and just run python pred_onnx.py， you can reproduce the error\r\n\r\nI have seen the link, it shows up as empty folder.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1138874511/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1139200667",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11548#issuecomment-1139200667",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11548",
        "id": 1139200667,
        "node_id": "IC_kwDOCVq1mM5D5tKb",
        "user": {
            "login": "pythondever",
            "id": 24561457,
            "node_id": "MDQ6VXNlcjI0NTYxNDU3",
            "avatar_url": "https://avatars.githubusercontent.com/u/24561457?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/pythondever",
            "html_url": "https://github.com/pythondever",
            "followers_url": "https://api.github.com/users/pythondever/followers",
            "following_url": "https://api.github.com/users/pythondever/following{/other_user}",
            "gists_url": "https://api.github.com/users/pythondever/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/pythondever/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/pythondever/subscriptions",
            "organizations_url": "https://api.github.com/users/pythondever/orgs",
            "repos_url": "https://api.github.com/users/pythondever/repos",
            "events_url": "https://api.github.com/users/pythondever/events{/privacy}",
            "received_events_url": "https://api.github.com/users/pythondever/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-05-27T01:41:38Z",
        "updated_at": "2022-05-27T01:41:38Z",
        "author_association": "NONE",
        "body": "> > @yuslepukhin thanks reply！ I push my demo program please follow this url [https://github.com/pythondever/_onnx_demo_error](url) and just run python pred_onnx.py， you can reproduce the error\r\n> \r\n> I have seen the link, it shows up as empty folder.\r\n\r\nreally sorry，I copied the address again，It's ready to go，\r\n\r\nhttps://github.com/pythondever/_onnx_demo_error\r\n",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1139200667/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1140951018",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11548#issuecomment-1140951018",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11548",
        "id": 1140951018,
        "node_id": "IC_kwDOCVq1mM5EAYfq",
        "user": {
            "login": "Eliza-and-black",
            "id": 55172223,
            "node_id": "MDQ6VXNlcjU1MTcyMjIz",
            "avatar_url": "https://avatars.githubusercontent.com/u/55172223?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Eliza-and-black",
            "html_url": "https://github.com/Eliza-and-black",
            "followers_url": "https://api.github.com/users/Eliza-and-black/followers",
            "following_url": "https://api.github.com/users/Eliza-and-black/following{/other_user}",
            "gists_url": "https://api.github.com/users/Eliza-and-black/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Eliza-and-black/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Eliza-and-black/subscriptions",
            "organizations_url": "https://api.github.com/users/Eliza-and-black/orgs",
            "repos_url": "https://api.github.com/users/Eliza-and-black/repos",
            "events_url": "https://api.github.com/users/Eliza-and-black/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Eliza-and-black/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-05-30T09:55:25Z",
        "updated_at": "2022-05-30T09:55:25Z",
        "author_association": "NONE",
        "body": "I got a similar error:\r\n\"onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Mul node. Name:'Mul_710' Status Message: Mul_710: right operand cannot broadcast on dim 3 LeftShape: {1,3,15,25,2}, RightShape: {1,3,20,20,2}\"\r\n",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1140951018/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1144405702",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11548#issuecomment-1144405702",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11548",
        "id": 1144405702,
        "node_id": "IC_kwDOCVq1mM5ENj7G",
        "user": {
            "login": "beyonehan",
            "id": 19468927,
            "node_id": "MDQ6VXNlcjE5NDY4OTI3",
            "avatar_url": "https://avatars.githubusercontent.com/u/19468927?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/beyonehan",
            "html_url": "https://github.com/beyonehan",
            "followers_url": "https://api.github.com/users/beyonehan/followers",
            "following_url": "https://api.github.com/users/beyonehan/following{/other_user}",
            "gists_url": "https://api.github.com/users/beyonehan/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/beyonehan/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/beyonehan/subscriptions",
            "organizations_url": "https://api.github.com/users/beyonehan/orgs",
            "repos_url": "https://api.github.com/users/beyonehan/repos",
            "events_url": "https://api.github.com/users/beyonehan/events{/privacy}",
            "received_events_url": "https://api.github.com/users/beyonehan/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-06-02T03:50:39Z",
        "updated_at": "2022-06-02T03:50:39Z",
        "author_association": "NONE",
        "body": "> 2022-05-17 17:30:35.309693323 [E:onnxruntime:Default, cuda_call.cc:118 CudaCall] CUDNN failure 3: CUDNN_STATUS_BAD_PARAM ; GPU=0 ; hostname=pc-Z390-GAMING-X ; expr=cudnnAddTensor(Base::CudnnHandle(), &alpha, Base::s_.z_tensor, Base::s_.z_data, &alpha, Base::s_.y_tensor, Base::s_.y_data)\r\n\r\n\r\n> \r\n\r\nHi , I am really looking forward your answer.Many thanks. I have same problem with [pythondever](https://github.com/pythondever). I have tired everything that I could do for that problems, but it still remains.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1144405702/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1156365454",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11548#issuecomment-1156365454",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11548",
        "id": 1156365454,
        "node_id": "IC_kwDOCVq1mM5E7LyO",
        "user": {
            "login": "hosea7456",
            "id": 48872586,
            "node_id": "MDQ6VXNlcjQ4ODcyNTg2",
            "avatar_url": "https://avatars.githubusercontent.com/u/48872586?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/hosea7456",
            "html_url": "https://github.com/hosea7456",
            "followers_url": "https://api.github.com/users/hosea7456/followers",
            "following_url": "https://api.github.com/users/hosea7456/following{/other_user}",
            "gists_url": "https://api.github.com/users/hosea7456/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/hosea7456/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/hosea7456/subscriptions",
            "organizations_url": "https://api.github.com/users/hosea7456/orgs",
            "repos_url": "https://api.github.com/users/hosea7456/repos",
            "events_url": "https://api.github.com/users/hosea7456/events{/privacy}",
            "received_events_url": "https://api.github.com/users/hosea7456/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-06-15T11:40:40Z",
        "updated_at": "2022-06-15T11:40:40Z",
        "author_association": "NONE",
        "body": "@yuslepukhin \r\nI recently came across the same issue when I running my code.\r\n**Describe the bug:**\r\nonnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running FusedConv node. Name:'p2o.Conv.68' Status Message: CUDNN error executing cudnnAddTensor(Base::CudnnHandle(), &alpha, Base::s_.z_tensor, Base::s_.z_data, &alpha, Base::s_.y_tensor, Base::s_.y_data)\r\n\r\n**And my model can be get by the following link:**\r\nhttps://drive.google.com/file/d/1GiNLsQropC2YJtlmWW2z6RWBVwcyDEQh/view?usp=sharing\r\n\r\nAny help will be gratefully appreciated!",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1156365454/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1156722372",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11548#issuecomment-1156722372",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11548",
        "id": 1156722372,
        "node_id": "IC_kwDOCVq1mM5E8i7E",
        "user": {
            "login": "yuslepukhin",
            "id": 11303988,
            "node_id": "MDQ6VXNlcjExMzAzOTg4",
            "avatar_url": "https://avatars.githubusercontent.com/u/11303988?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/yuslepukhin",
            "html_url": "https://github.com/yuslepukhin",
            "followers_url": "https://api.github.com/users/yuslepukhin/followers",
            "following_url": "https://api.github.com/users/yuslepukhin/following{/other_user}",
            "gists_url": "https://api.github.com/users/yuslepukhin/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/yuslepukhin/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/yuslepukhin/subscriptions",
            "organizations_url": "https://api.github.com/users/yuslepukhin/orgs",
            "repos_url": "https://api.github.com/users/yuslepukhin/repos",
            "events_url": "https://api.github.com/users/yuslepukhin/events{/privacy}",
            "received_events_url": "https://api.github.com/users/yuslepukhin/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-06-15T17:05:21Z",
        "updated_at": "2022-06-15T17:05:21Z",
        "author_association": "MEMBER",
        "body": "> I got a similar error: \"onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Mul node. Name:'Mul_710' Status Message: Mul_710: right operand cannot broadcast on dim 3 LeftShape: {1,3,15,25,2}, RightShape: {1,3,20,20,2}\"\r\n\r\nThis is a very different issue and problem is in the model. The two shapes can not be broadcasted. Please, report this separate.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1156722372/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1156724230",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11548#issuecomment-1156724230",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11548",
        "id": 1156724230,
        "node_id": "IC_kwDOCVq1mM5E8jYG",
        "user": {
            "login": "yuslepukhin",
            "id": 11303988,
            "node_id": "MDQ6VXNlcjExMzAzOTg4",
            "avatar_url": "https://avatars.githubusercontent.com/u/11303988?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/yuslepukhin",
            "html_url": "https://github.com/yuslepukhin",
            "followers_url": "https://api.github.com/users/yuslepukhin/followers",
            "following_url": "https://api.github.com/users/yuslepukhin/following{/other_user}",
            "gists_url": "https://api.github.com/users/yuslepukhin/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/yuslepukhin/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/yuslepukhin/subscriptions",
            "organizations_url": "https://api.github.com/users/yuslepukhin/orgs",
            "repos_url": "https://api.github.com/users/yuslepukhin/repos",
            "events_url": "https://api.github.com/users/yuslepukhin/events{/privacy}",
            "received_events_url": "https://api.github.com/users/yuslepukhin/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-06-15T17:07:01Z",
        "updated_at": "2022-06-15T17:07:01Z",
        "author_association": "MEMBER",
        "body": "> > > @yuslepukhin thanks reply！ I push my demo program please follow this url [https://github.com/pythondever/_onnx_demo_error](url) and just run python pred_onnx.py， you can reproduce the error\r\n> > \r\n> > \r\n> > I have seen the link, it shows up as empty folder.\r\n> \r\n> really sorry，I copied the address again，It's ready to go，\r\n> \r\n> https://github.com/pythondever/_onnx_demo_error\r\n\r\nThis still does not open. ",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1156724230/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1156724974",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11548#issuecomment-1156724974",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11548",
        "id": 1156724974,
        "node_id": "IC_kwDOCVq1mM5E8jju",
        "user": {
            "login": "yuslepukhin",
            "id": 11303988,
            "node_id": "MDQ6VXNlcjExMzAzOTg4",
            "avatar_url": "https://avatars.githubusercontent.com/u/11303988?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/yuslepukhin",
            "html_url": "https://github.com/yuslepukhin",
            "followers_url": "https://api.github.com/users/yuslepukhin/followers",
            "following_url": "https://api.github.com/users/yuslepukhin/following{/other_user}",
            "gists_url": "https://api.github.com/users/yuslepukhin/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/yuslepukhin/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/yuslepukhin/subscriptions",
            "organizations_url": "https://api.github.com/users/yuslepukhin/orgs",
            "repos_url": "https://api.github.com/users/yuslepukhin/repos",
            "events_url": "https://api.github.com/users/yuslepukhin/events{/privacy}",
            "received_events_url": "https://api.github.com/users/yuslepukhin/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-06-15T17:07:46Z",
        "updated_at": "2022-06-15T17:07:46Z",
        "author_association": "MEMBER",
        "body": "> @yuslepukhin I recently came across the same issue when I running my code. **Describe the bug:** onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running FusedConv node. Name:'p2o.Conv.68' Status Message: CUDNN error executing cudnnAddTensor(Base::CudnnHandle(), &alpha, Base::s_.z_tensor, Base::s_.z_data, &alpha, Base::s_.y_tensor, Base::s_.y_data)\r\n> \r\n> **And my model can be get by the following link:** https://drive.google.com/file/d/1GiNLsQropC2YJtlmWW2z6RWBVwcyDEQh/view?usp=sharing\r\n> \r\n> Any help will be gratefully appreciated!\r\n\r\nGot this, would be nice if you shared a script to drive this with inputs. Does this work on CPU?",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1156724974/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1157187844",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11548#issuecomment-1157187844",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11548",
        "id": 1157187844,
        "node_id": "IC_kwDOCVq1mM5E-UkE",
        "user": {
            "login": "hosea7456",
            "id": 48872586,
            "node_id": "MDQ6VXNlcjQ4ODcyNTg2",
            "avatar_url": "https://avatars.githubusercontent.com/u/48872586?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/hosea7456",
            "html_url": "https://github.com/hosea7456",
            "followers_url": "https://api.github.com/users/hosea7456/followers",
            "following_url": "https://api.github.com/users/hosea7456/following{/other_user}",
            "gists_url": "https://api.github.com/users/hosea7456/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/hosea7456/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/hosea7456/subscriptions",
            "organizations_url": "https://api.github.com/users/hosea7456/orgs",
            "repos_url": "https://api.github.com/users/hosea7456/repos",
            "events_url": "https://api.github.com/users/hosea7456/events{/privacy}",
            "received_events_url": "https://api.github.com/users/hosea7456/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-06-16T03:22:27Z",
        "updated_at": "2022-06-16T03:22:27Z",
        "author_association": "NONE",
        "body": "> > @yuslepukhin I recently came across the same issue when I running my code. **Describe the bug:** onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running FusedConv node. Name:'p2o.Conv.68' Status Message: CUDNN error executing cudnnAddTensor(Base::CudnnHandle(), &alpha, Base::s_.z_tensor, Base::s_.z_data, &alpha, Base::s_.y_tensor, Base::s_.y_data)\r\n> > **And my model can be get by the following link:** https://drive.google.com/file/d/1GiNLsQropC2YJtlmWW2z6RWBVwcyDEQh/view?usp=sharing\r\n> > Any help will be gratefully appreciated!\r\n> \r\n> Got this, would be nice if you shared a script to drive this with inputs. Does this work on CPU?\r\n\r\nMany thanks for your immediate reply!\r\nYes,  it runs well on CPU but filed to run on GPU. And my environment information is: ONNXRuntime 1.11.1, CUDA11.4, CUDNN8.2\r\nHere is the code for running inference. \r\nhttps://drive.google.com/drive/folders/1fWoIE2q1t6DJYgyvCIPQcwrsZjdXR4rY?usp=sharing",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1157187844/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1158314424",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11548#issuecomment-1158314424",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11548",
        "id": 1158314424,
        "node_id": "IC_kwDOCVq1mM5FCnm4",
        "user": {
            "login": "yuslepukhin",
            "id": 11303988,
            "node_id": "MDQ6VXNlcjExMzAzOTg4",
            "avatar_url": "https://avatars.githubusercontent.com/u/11303988?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/yuslepukhin",
            "html_url": "https://github.com/yuslepukhin",
            "followers_url": "https://api.github.com/users/yuslepukhin/followers",
            "following_url": "https://api.github.com/users/yuslepukhin/following{/other_user}",
            "gists_url": "https://api.github.com/users/yuslepukhin/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/yuslepukhin/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/yuslepukhin/subscriptions",
            "organizations_url": "https://api.github.com/users/yuslepukhin/orgs",
            "repos_url": "https://api.github.com/users/yuslepukhin/repos",
            "events_url": "https://api.github.com/users/yuslepukhin/events{/privacy}",
            "received_events_url": "https://api.github.com/users/yuslepukhin/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-06-17T00:12:51Z",
        "updated_at": "2022-06-17T00:12:51Z",
        "author_association": "MEMBER",
        "body": "I have been able to reproduce your issue. For an immediate workaround you enable only basic optimizations for CUDA runs.\r\n`sess_opt = ort.SessionOptions()`\r\n` sess_opt.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_BASIC`\r\n`session = ort.InferenceSession(args.onnx_file_path, sess_options=sess_opt, providers=providers)`\r\n\r\nThis will likely result in some performance loss, while you are waiting for a fix.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1158314424/reactions",
            "total_count": 3,
            "+1": 3,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1159368367",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11548#issuecomment-1159368367",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11548",
        "id": 1159368367,
        "node_id": "IC_kwDOCVq1mM5FGo6v",
        "user": {
            "login": "pythondever",
            "id": 24561457,
            "node_id": "MDQ6VXNlcjI0NTYxNDU3",
            "avatar_url": "https://avatars.githubusercontent.com/u/24561457?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/pythondever",
            "html_url": "https://github.com/pythondever",
            "followers_url": "https://api.github.com/users/pythondever/followers",
            "following_url": "https://api.github.com/users/pythondever/following{/other_user}",
            "gists_url": "https://api.github.com/users/pythondever/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/pythondever/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/pythondever/subscriptions",
            "organizations_url": "https://api.github.com/users/pythondever/orgs",
            "repos_url": "https://api.github.com/users/pythondever/repos",
            "events_url": "https://api.github.com/users/pythondever/events{/privacy}",
            "received_events_url": "https://api.github.com/users/pythondever/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-06-18T05:47:30Z",
        "updated_at": "2022-06-18T05:47:30Z",
        "author_association": "NONE",
        "body": "> ort.GraphOptimizationLevel.ORT_ENABLE_BASIC\r\n\r\nYes, it works now  thanks!",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1159368367/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1161339833",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11548#issuecomment-1161339833",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11548",
        "id": 1161339833,
        "node_id": "IC_kwDOCVq1mM5FOKO5",
        "user": {
            "login": "hosea7456",
            "id": 48872586,
            "node_id": "MDQ6VXNlcjQ4ODcyNTg2",
            "avatar_url": "https://avatars.githubusercontent.com/u/48872586?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/hosea7456",
            "html_url": "https://github.com/hosea7456",
            "followers_url": "https://api.github.com/users/hosea7456/followers",
            "following_url": "https://api.github.com/users/hosea7456/following{/other_user}",
            "gists_url": "https://api.github.com/users/hosea7456/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/hosea7456/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/hosea7456/subscriptions",
            "organizations_url": "https://api.github.com/users/hosea7456/orgs",
            "repos_url": "https://api.github.com/users/hosea7456/repos",
            "events_url": "https://api.github.com/users/hosea7456/events{/privacy}",
            "received_events_url": "https://api.github.com/users/hosea7456/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-06-21T07:00:07Z",
        "updated_at": "2022-06-21T07:00:07Z",
        "author_association": "NONE",
        "body": "> I have been able to reproduce your issue. For an immediate workaround you enable only basic optimizations for CUDA runs. `sess_opt = ort.SessionOptions()` ` sess_opt.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_BASIC` `session = ort.InferenceSession(args.onnx_file_path, sess_options=sess_opt, providers=providers)`\r\n> \r\n> This will likely result in some performance loss, while you are waiting for a fix.\r\n\r\nThe problem was solved, thanks a lot. And looking forwaord the fix version!",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1161339833/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]